export interface CompCheck {
  id: string;
  label: string;
  detail?: string;
  priority: "must" | "should" | "nice";
}

export interface CompCategory {
  id: string;
  title: string;
  icon: string;
  description: string;
  checks: CompCheck[];
}

export const competitorSopData: CompCategory[] = [
  {
    id: "identify-competitors",
    title: "Competitor Identification",
    icon: "🎯",
    description: "Identify the right competitors — analyzing the wrong ones is a waste of time",
    checks: [
      { id: "ci-01", label: "Search primary keyword on Google — note top 10 results", priority: "must" },
      { id: "ci-02", label: "Identify direct business competitors (same service/product)", priority: "must" },
      { id: "ci-03", label: "Identify search competitors (ranking for same keywords in SERP)", priority: "must" },
      { id: "ci-04", label: "Keep direct vs search competitors in separate lists — they are different", priority: "must" },
      { id: "ci-05", label: "Note top 5 SERP competitors (organic results)", priority: "must" },
      { id: "ci-06", label: "Identify local competitors (if local SEO)", priority: "must" },
      { id: "ci-07", label: "Identify national competitors", priority: "should" },
      { id: "ci-08", label: "Identify indirect competitors — different product, same audience", priority: "should" },
      { id: "ci-09", label: "Separate out big authority sites (Wikipedia, Forbes etc) — they are not real competitors", priority: "must" },
      { id: "ci-10", label: "Select min 3, max 5 core competitors for deep analysis", priority: "must" },
      { id: "ci-11", label: "Confirm competitor list with client before deep analysis", priority: "should" },
      { id: "ci-12", label: "Identify niche-specific directories / aggregators (could be competitors)", priority: "should" },
      { id: "ci-13", label: "Identify YouTube competitors (if video intent exists)", priority: "nice" },
      { id: "ci-14", label: "Identify social media competitors", priority: "nice" },
      { id: "ci-15", label: "Save competitor list in document with URLs", priority: "must" },
    ],
  },
  {
    id: "domain-analysis",
    title: "Domain & Authority Analysis",
    icon: "🌐",
    description: "Understand the overall domain strength of each competitor",
    checks: [
      { id: "da-01", label: "Check Domain Authority (DA) — Moz / Ahrefs / free tools", priority: "must" },
      { id: "da-02", label: "Check Domain Rating (DR) — Ahrefs scale", priority: "should" },
      { id: "da-03", label: "Check domain age — how many years has the site existed", priority: "must" },
      { id: "da-04", label: "Check total referring domains", priority: "must" },
      { id: "da-05", label: "Check total backlinks count", priority: "must" },
      { id: "da-06", label: "Check organic traffic estimate (Semrush/Ahrefs/Ubersuggest)", priority: "must" },
      { id: "da-07", label: "Check total keywords ranking", priority: "must" },
      { id: "da-08", label: "Note top organic pages", priority: "must" },
      { id: "da-09", label: "Review traffic trend — growing/declining/stable", priority: "must" },
      { id: "da-10", label: "Check site speed — PageSpeed Insights", priority: "should" },
      { id: "da-11", label: "Check mobile-friendliness", priority: "should" },
      { id: "da-12", label: "Check HTTPS — is site secure?", priority: "must" },
      { id: "da-13", label: "Check Core Web Vitals status", priority: "should" },
      { id: "da-14", label: "Note site structure — categories, URL structure", priority: "should" },
      { id: "da-15", label: "Check number of indexed pages (site:domain.com Google search)", priority: "must" },
      { id: "da-16", label: "Check spam score — high spam = weak competitor", priority: "should" },
      { id: "da-17", label: "Note social media presence — followers/engagement", priority: "nice" },
      { id: "da-18", label: "Note Alexa/SimilarWeb ranking", priority: "nice" },
      { id: "da-19", label: "Compile all data into one comparison table", priority: "must" },
      { id: "da-20", label: "Compare against your own site — identify the gap", priority: "must" },
    ],
  },
  {
    id: "keyword-gap",
    title: "Keyword Gap Analysis",
    icon: "🔑",
    description: "Keywords competitors rank for that you are missing — this is gold",
    checks: [
      { id: "kg-01", label: "List competitor's top ranking keywords", priority: "must" },
      { id: "kg-02", label: "Compare with your keywords — identify the gap", priority: "must" },
      { id: "kg-03", label: "Use keyword gap tool — Semrush/Ahrefs/Ubersuggest", priority: "must" },
      { id: "kg-04", label: "Note competitor-only keywords (you do not rank for these)", priority: "must" },
      { id: "kg-05", label: "Note shared keywords (both rank for these)", priority: "must" },
      { id: "kg-06", label: "Note your-only keywords (competitor does not rank)", priority: "should" },
      { id: "kg-07", label: "Prioritize high volume competitor gap keywords", priority: "must" },
      { id: "kg-08", label: "Identify low difficulty gap keywords — quick wins", priority: "must" },
      { id: "kg-09", label: "Note competitor long-tail keywords", priority: "must" },
      { id: "kg-10", label: "Note competitor question-based keywords", priority: "must" },
      { id: "kg-11", label: "Note competitor local keywords", priority: "must" },
      { id: "kg-12", label: "Compare commercial intent keywords", priority: "must" },
      { id: "kg-13", label: "Note competitor brand keywords", priority: "should" },
      { id: "kg-14", label: "Note competitor seasonal keywords", priority: "nice" },
      { id: "kg-15", label: "Build content plan from gap keywords — new pages needed", priority: "must" },
      { id: "kg-16", label: "Optimize existing pages for gap keywords", priority: "must" },
      { id: "kg-17", label: "Present keyword gap report to client", priority: "should" },
      { id: "kg-18", label: "Set priority order — target high impact gap keywords first", priority: "must" },
      { id: "kg-19", label: "Note featured snippet competitor keywords", priority: "should" },
      { id: "kg-20", label: "Note PAA box competitor keywords", priority: "should" },
    ],
  },
  {
    id: "content-analysis",
    title: "Competitor Content Analysis",
    icon: "📄",
    description: "Study competitor content — plan to write better",
    checks: [
      { id: "ca-01", label: "Note top 5 performing competitor pages (by traffic)", priority: "must" },
      { id: "ca-02", label: "Note content type of each top page — blog/guide/tool/comparison", priority: "must" },
      { id: "ca-03", label: "Note average word count of top pages", priority: "must" },
      { id: "ca-04", label: "Note content format — listicle/how-to/case study/review", priority: "must" },
      { id: "ca-05", label: "Note H1, H2, H3 structure of important pages", priority: "must" },
      { id: "ca-06", label: "Check content freshness — last updated when", priority: "must" },
      { id: "ca-07", label: "Check update frequency — how often they refresh content", priority: "should" },
      { id: "ca-08", label: "Check content depth — surface level or comprehensive", priority: "must" },
      { id: "ca-09", label: "What they cover well — note strengths", priority: "must" },
      { id: "ca-10", label: "What they miss — note gaps (opportunity for you)", priority: "must" },
      { id: "ca-11", label: "Note content tone / style — formal/casual/technical", priority: "should" },
      { id: "ca-12", label: "Check multimedia use — images/videos/infographics", priority: "should" },
      { id: "ca-13", label: "Is interactive content present? Tools/calculators/quizzes", priority: "nice" },
      { id: "ca-14", label: "Is user-generated content present? Reviews/comments/forum", priority: "nice" },
      { id: "ca-15", label: "Note blog publishing frequency", priority: "must" },
      { id: "ca-16", label: "Identify content hub / pillar pages", priority: "must" },
      { id: "ca-17", label: "Identify topic clusters — which topics do they dominate", priority: "must" },
      { id: "ca-18", label: "Identify outdated content — opportunity to publish a better version", priority: "must" },
      { id: "ca-19", label: "Identify thin content pages — easier to rank against", priority: "must" },
      { id: "ca-20", label: "Do they publish original research / data?", priority: "should" },
      { id: "ca-21", label: "Do they have case studies / success stories?", priority: "should" },
      { id: "ca-22", label: "Do they consistently use FAQ sections?", priority: "should" },
      { id: "ca-23", label: "Are E-E-A-T signals strong in their content?", priority: "should" },
      { id: "ca-24", label: "Are they using schema markup?", priority: "should" },
      { id: "ca-25", label: "Write content strategy summary — what is the overall pattern?", priority: "must" },
    ],
  },
  {
    id: "onpage-analysis",
    title: "Competitor On-Page SEO Analysis",
    icon: "🔍",
    description: "Review competitor on-page factors and compare against yours",
    checks: [
      { id: "oa-01", label: "Note title tag format — what pattern do they follow", priority: "must" },
      { id: "oa-02", label: "Check title tag length — average characters", priority: "must" },
      { id: "oa-03", label: "Note meta description pattern", priority: "must" },
      { id: "oa-04", label: "Note URL structure — clean or messy", priority: "must" },
      { id: "oa-05", label: "Analyze H1 format — keyword placement", priority: "must" },
      { id: "oa-06", label: "Note H2 structure pattern", priority: "must" },
      { id: "oa-07", label: "Review internal linking strategy — how many links, where", priority: "must" },
      { id: "oa-08", label: "Check image optimization — alt texts, file names", priority: "should" },
      { id: "oa-09", label: "Do they use breadcrumbs?", priority: "should" },
      { id: "oa-10", label: "Do they use table of contents?", priority: "should" },
      { id: "oa-11", label: "Note schema markup types used", priority: "must" },
      { id: "oa-12", label: "Have they captured featured snippet? What format?", priority: "must" },
      { id: "oa-13", label: "Which SERP features have they captured?", priority: "must" },
      { id: "oa-14", label: "Note CTA placement — where and how", priority: "should" },
      { id: "oa-15", label: "Note page layout / UX — clean or cluttered", priority: "should" },
      { id: "oa-16", label: "Do they use pop-ups / interstitials?", priority: "nice" },
      { id: "oa-17", label: "Roughly estimate keyword density", priority: "should" },
      { id: "oa-18", label: "Do they use LSI / related terms?", priority: "should" },
      { id: "oa-19", label: "What NLP entities do they mention?", priority: "should" },
      { id: "oa-20", label: "Build on-page comparison table — yours vs competitor", priority: "must" },
    ],
  },
  {
    id: "backlink-analysis",
    title: "Competitor Backlink Analysis",
    icon: "🔗",
    description: "Study their links — then target the same sources",
    checks: [
      { id: "ba-01", label: "Note total backlinks count", priority: "must" },
      { id: "ba-02", label: "Note total referring domains count", priority: "must" },
      { id: "ba-03", label: "List top referring domains (top 20)", priority: "must" },
      { id: "ba-04", label: "Identify high DA linking domains", priority: "must" },
      { id: "ba-05", label: "Analyze link types — editorial/directory/forum/guest post", priority: "must" },
      { id: "ba-06", label: "Identify most linked pages (link magnets)", priority: "must" },
      { id: "ba-07", label: "Analyze anchor text distribution", priority: "must" },
      { id: "ba-08", label: "Check over-optimized anchor text — risk signal", priority: "should" },
      { id: "ba-09", label: "Check new backlinks trend — how many gained recently", priority: "should" },
      { id: "ba-10", label: "Check lost backlinks — where did links go", priority: "should" },
      { id: "ba-11", label: "Find guest post placements — where did they guest post", priority: "must" },
      { id: "ba-12", label: "Identify resource page links", priority: "should" },
      { id: "ba-13", label: "Identify directory listings — submit to same ones", priority: "must" },
      { id: "ba-14", label: "Identify broken links on competitor site — outreach opportunity", priority: "should" },
      { id: "ba-15", label: "Find unlinked brand mentions — link reclamation opportunity", priority: "nice" },
      { id: "ba-16", label: "Identify common link sources — sites linking to multiple competitors", priority: "must" },
      { id: "ba-17", label: "Analyze link velocity — month by month growth", priority: "should" },
      { id: "ba-18", label: "Note toxic / spammy links ratio", priority: "should" },
      { id: "ba-19", label: "Identify local citations / NAP links", priority: "must" },
      { id: "ba-20", label: "Build backlink gap report — sources that linked to competitors but not you", priority: "must" },
      { id: "ba-21", label: "Prioritize top 10 backlink opportunities for outreach", priority: "must" },
      { id: "ba-22", label: "Identify PR / media links — which publications covered them", priority: "should" },
      { id: "ba-23", label: "Note social profile links", priority: "nice" },
      { id: "ba-24", label: "Identify edu / gov links — how did they get them", priority: "nice" },
      { id: "ba-25", label: "Write link building strategy summary based on analysis", priority: "must" },
    ],
  },
  {
    id: "technical-comparison",
    title: "Technical SEO Comparison",
    icon: "⚙️",
    description: "Find technical advantages competitors have that you are missing",
    checks: [
      { id: "tc-01", label: "Compare page speed — GTmetrix/PageSpeed Insights", priority: "must" },
      { id: "tc-02", label: "Compare Core Web Vitals — LCP/CLS/FID", priority: "must" },
      { id: "tc-03", label: "Compare mobile score", priority: "must" },
      { id: "tc-04", label: "Compare HTTPS status", priority: "must" },
      { id: "tc-05", label: "Have they submitted XML sitemap?", priority: "should" },
      { id: "tc-06", label: "Is robots.txt properly configured?", priority: "should" },
      { id: "tc-07", label: "Check crawl errors — Screaming Frog lite or GSC", priority: "should" },
      { id: "tc-08", label: "Do they use canonical tags properly?", priority: "should" },
      { id: "tc-09", label: "Do they use hreflang tags (multilingual)?", priority: "nice" },
      { id: "tc-10", label: "Compare structured data implementation", priority: "must" },
      { id: "tc-11", label: "Image optimization — do they use WebP?", priority: "should" },
      { id: "tc-12", label: "Have they implemented lazy loading?", priority: "should" },
      { id: "tc-13", label: "Do they use a CDN?", priority: "nice" },
      { id: "tc-14", label: "Compare server response time", priority: "should" },
      { id: "tc-15", label: "Is site JavaScript-heavy — crawlability issue?", priority: "should" },
      { id: "tc-16", label: "Is pagination properly handled?", priority: "nice" },
      { id: "tc-17", label: "Do they have duplicate content issues?", priority: "should" },
      { id: "tc-18", label: "How many 404 errors do they have?", priority: "should" },
      { id: "tc-19", label: "Do they have redirect chains?", priority: "should" },
      { id: "tc-20", label: "Summarize technical gaps — where you are better and where you are not", priority: "must" },
    ],
  },
  {
    id: "local-competitor",
    title: "Local SEO Competitor Analysis",
    icon: "📍",
    description: "Competitor analysis for local pack and map rankings",
    checks: [
      { id: "lc-01", label: "Has competitor claimed Google Business Profile (GBP)?", priority: "must" },
      { id: "lc-02", label: "Note GBP category — primary and secondary categories", priority: "must" },
      { id: "lc-03", label: "Note GBP review count", priority: "must" },
      { id: "lc-04", label: "Note GBP average rating", priority: "must" },
      { id: "lc-05", label: "Check GBP review response rate", priority: "should" },
      { id: "lc-06", label: "Note GBP photos count", priority: "should" },
      { id: "lc-07", label: "Check GBP post frequency — how often do they post", priority: "should" },
      { id: "lc-08", label: "Review GBP Q&A section — what questions are listed", priority: "should" },
      { id: "lc-09", label: "Are GBP services/products listed?", priority: "should" },
      { id: "lc-10", label: "What position are they in local pack — 1st/2nd/3rd", priority: "must" },
      { id: "lc-11", label: "Check NAP consistency — Name/Address/Phone same everywhere?", priority: "must" },
      { id: "lc-12", label: "Compare local citations count", priority: "must" },
      { id: "lc-13", label: "Note citation sources — where are they listed", priority: "must" },
      { id: "lc-14", label: "Do they have local landing pages? How many cities?", priority: "must" },
      { id: "lc-15", label: "Do they use local schema markup?", priority: "must" },
      { id: "lc-16", label: "Local backlinks — links from local news/blogs/directories?", priority: "should" },
      { id: "lc-17", label: "Local content strategy — do they have city-specific blog posts?", priority: "should" },
      { id: "lc-18", label: "Service area coverage — how many areas do they cover", priority: "should" },
      { id: "lc-19", label: "Local trust signals — awards, community mentions", priority: "nice" },
      { id: "lc-20", label: "Build local competitor comparison table — your GBP vs theirs", priority: "must" },
    ],
  },
  {
    id: "social-brand",
    title: "Social Media & Brand Analysis",
    icon: "📱",
    description: "Compare brand presence and social signals",
    checks: [
      { id: "sb-01", label: "Note Facebook page followers", priority: "should" },
      { id: "sb-02", label: "Note Instagram followers", priority: "should" },
      { id: "sb-03", label: "Note LinkedIn followers", priority: "should" },
      { id: "sb-04", label: "Note Twitter/X followers", priority: "nice" },
      { id: "sb-05", label: "Note YouTube subscribers/views", priority: "should" },
      { id: "sb-06", label: "Check TikTok presence (if relevant niche)", priority: "nice" },
      { id: "sb-07", label: "Note social posting frequency", priority: "should" },
      { id: "sb-08", label: "Roughly estimate engagement rate", priority: "should" },
      { id: "sb-09", label: "Note social content type — video/image/text/reels", priority: "nice" },
      { id: "sb-10", label: "Track brand mentions online — where are they being discussed", priority: "should" },
      { id: "sb-11", label: "Note press coverage / PR articles", priority: "should" },
      { id: "sb-12", label: "Check online reputation — review platforms (Trustpilot/G2/Yelp)", priority: "must" },
      { id: "sb-13", label: "Roughly compare brand search volume", priority: "should" },
      { id: "sb-14", label: "Do they have a Knowledge Panel?", priority: "should" },
      { id: "sb-15", label: "Do they have a Wikipedia page?", priority: "nice" },
      { id: "sb-16", label: "Do they have a podcast?", priority: "nice" },
      { id: "sb-17", label: "Community/forum presence? Reddit, Quora answers", priority: "nice" },
      { id: "sb-18", label: "Note influencer partnerships", priority: "nice" },
      { id: "sb-19", label: "Do they publish an email newsletter?", priority: "nice" },
      { id: "sb-20", label: "Note brand positioning — how do they present themselves", priority: "must" },
    ],
  },
  {
    id: "serp-features",
    title: "SERP Features Competitor Analysis",
    icon: "📊",
    description: "Which SERP features is the competitor capturing — where are you missing out",
    checks: [
      { id: "sf-01", label: "Who owns the featured snippet — competitor or you?", priority: "must" },
      { id: "sf-02", label: "Note featured snippet format — paragraph/list/table", priority: "must" },
      { id: "sf-03", label: "Whose content appears in PAA boxes?", priority: "must" },
      { id: "sf-04", label: "Compare local pack positions", priority: "must" },
      { id: "sf-05", label: "Whose image appears in image pack?", priority: "should" },
      { id: "sf-06", label: "Which competitors appear in video carousel?", priority: "should" },
      { id: "sf-07", label: "Does competitor have a Knowledge Panel?", priority: "should" },
      { id: "sf-08", label: "Are they in shopping results?", priority: "nice" },
      { id: "sf-09", label: "Who has sitelinks?", priority: "should" },
      { id: "sf-10", label: "Who has review stars (rich results)?", priority: "must" },
      { id: "sf-11", label: "Whose FAQ rich results appear?", priority: "must" },
      { id: "sf-12", label: "Who has HowTo rich results?", priority: "should" },
      { id: "sf-13", label: "Whose content appears in AI Overview (Google SGE)?", priority: "must" },
      { id: "sf-14", label: "Are they in top stories / news box?", priority: "nice" },
      { id: "sf-15", label: "Build SERP features opportunity list — where can you capture them", priority: "must" },
    ],
  },
  {
    id: "content-gap-opportunity",
    title: "Content Gap & Opportunity",
    icon: "💡",
    description: "This is where new content ideas come from — core of the report",
    checks: [
      { id: "cgo-01", label: "List topics competitors cover that you do not", priority: "must" },
      { id: "cgo-02", label: "List topics you cover that competitors do not — your strengths", priority: "must" },
      { id: "cgo-03", label: "Identify outdated info in competitor content — update opportunity", priority: "must" },
      { id: "cgo-04", label: "Identify thin competitor content pages — write a better version", priority: "must" },
      { id: "cgo-05", label: "Identify factual errors in competitor content", priority: "should" },
      { id: "cgo-06", label: "Sub-topics that nobody covers — untapped opportunity", priority: "must" },
      { id: "cgo-07", label: "Long-tail queries that competitors are missing", priority: "must" },
      { id: "cgo-08", label: "User questions that nobody is properly answering", priority: "must" },
      { id: "cgo-09", label: "Local content opportunities — city pages competitor does not have", priority: "must" },
      { id: "cgo-10", label: "Content format gaps — competitors have no video, you create one", priority: "should" },
      { id: "cgo-11", label: "Tools / calculators competitors have not built", priority: "nice" },
      { id: "cgo-12", label: "Original research opportunity — data nobody has published", priority: "should" },
      { id: "cgo-13", label: "Comparison content opportunity — 'Competitor A vs B' type", priority: "should" },
      { id: "cgo-14", label: "Seasonal content opportunity — competitors miss seasonal content?", priority: "should" },
      { id: "cgo-15", label: "FAQ gaps — questions nobody properly answers in SERP", priority: "must" },
      { id: "cgo-16", label: "Niche sub-topics — specialist content generalists miss", priority: "must" },
      { id: "cgo-17", label: "Content upgrade opportunity — competitor content exists, build a better version", priority: "must" },
      { id: "cgo-18", label: "Prioritize top 10 content opportunities", priority: "must" },
      { id: "cgo-19", label: "Add these opportunities to content calendar", priority: "must" },
      { id: "cgo-20", label: "Present gap analysis to client with recommendations", priority: "must" },
    ],
  },
  {
    id: "ad-commercial",
    title: "Ad & Commercial Strategy Analysis",
    icon: "💰",
    description: "Understand competitor paid strategy — integrated view with organic",
    checks: [
      { id: "ac-01", label: "Is competitor running Google Ads?", priority: "must" },
      { id: "ac-02", label: "Note PPC keywords — what are they paying for", priority: "must" },
      { id: "ac-03", label: "Analyze ad copy — what message are they using", priority: "should" },
      { id: "ac-04", label: "Analyze landing pages — where do they send paid traffic", priority: "should" },
      { id: "ac-05", label: "Roughly estimate ad spend", priority: "nice" },
      { id: "ac-06", label: "Are they running shopping ads?", priority: "nice" },
      { id: "ac-07", label: "Are they running retargeting ads?", priority: "nice" },
      { id: "ac-08", label: "Note pricing model — subscription/one-time/tiered", priority: "must" },
      { id: "ac-09", label: "Do they offer free trial / freemium?", priority: "should" },
      { id: "ac-10", label: "Note discount / promotional strategy", priority: "should" },
      { id: "ac-11", label: "Do they use lead magnets? — ebook/checklist/tool", priority: "should" },
      { id: "ac-12", label: "Do they do email marketing? Is there a newsletter signup?", priority: "should" },
      { id: "ac-13", label: "Do they have an affiliate program?", priority: "nice" },
      { id: "ac-14", label: "What is their USP / value proposition?", priority: "must" },
      { id: "ac-15", label: "Write commercial analysis summary — how they monetize vs how you do", priority: "must" },
    ],
  },
  {
    id: "weakness-analysis",
    title: "Competitor Weakness Analysis",
    icon: "⚠️",
    description: "Their weaknesses are your opportunities — this is where you win",
    checks: [
      { id: "wa-01", label: "Slow page speed? — opportunity for better UX", priority: "must" },
      { id: "wa-02", label: "Poor mobile experience?", priority: "must" },
      { id: "wa-03", label: "Outdated design / UX?", priority: "should" },
      { id: "wa-04", label: "Ranking with thin content — easily beatable", priority: "must" },
      { id: "wa-05", label: "Low review count / poor reviews?", priority: "must" },
      { id: "wa-06", label: "What are negative reviews saying — what can you fix that they cannot", priority: "must" },
      { id: "wa-07", label: "Social media is inactive?", priority: "nice" },
      { id: "wa-08", label: "Blog publishing stopped / very infrequent?", priority: "should" },
      { id: "wa-09", label: "No FAQ sections on their pages?", priority: "should" },
      { id: "wa-10", label: "No schema markup?", priority: "should" },
      { id: "wa-11", label: "Poor internal linking?", priority: "should" },
      { id: "wa-12", label: "No local SEO presence?", priority: "must" },
      { id: "wa-13", label: "Low E-E-A-T signals — no author, no credentials?", priority: "should" },
      { id: "wa-14", label: "Content not updated in years?", priority: "must" },
      { id: "wa-15", label: "No video content?", priority: "nice" },
      { id: "wa-16", label: "Poor CTA / conversion optimization?", priority: "should" },
      { id: "wa-17", label: "No email capture / lead magnets?", priority: "nice" },
      { id: "wa-18", label: "Technical issues — broken links, slow server?", priority: "should" },
      { id: "wa-19", label: "Poor backlink profile — spammy links?", priority: "should" },
      { id: "wa-20", label: "List top 5 competitor weaknesses — with actionable opportunities", priority: "must" },
    ],
  },
  {
    id: "monitoring",
    title: "Ongoing Competitor Monitoring",
    icon: "👁️",
    description: "Not a one-time task — track every month. Competitors keep changing.",
    checks: [
      { id: "mn-01", label: "Track competitor keyword ranking changes monthly", priority: "must" },
      { id: "mn-02", label: "Check new pages published by competitor — monthly", priority: "must" },
      { id: "mn-03", label: "Check new backlinks earned by competitor — monthly", priority: "must" },
      { id: "mn-04", label: "Set up Google Alerts for competitor brand name", priority: "must" },
      { id: "mn-05", label: "Subscribe to competitor blog — get email updates", priority: "should" },
      { id: "mn-06", label: "Follow competitor on social media", priority: "should" },
      { id: "mn-07", label: "Monitor competitor pricing changes", priority: "should" },
      { id: "mn-08", label: "Monitor competitor new features/products launched", priority: "should" },
      { id: "mn-09", label: "Monitor competitor GBP changes — reviews/photos/posts", priority: "must" },
      { id: "mn-10", label: "Track SERP position changes — weekly", priority: "must" },
      { id: "mn-11", label: "Check competitor traffic trend monthly", priority: "should" },
      { id: "mn-12", label: "Is a new competitor entering the market? Quarterly check", priority: "should" },
      { id: "mn-13", label: "Did competitor get hit by algorithm update? Check after core updates", priority: "must" },
      { id: "mn-14", label: "Did competitor rebrand or pivot? Note it", priority: "should" },
      { id: "mn-15", label: "Build monthly competitor report — changes summary", priority: "must" },
      { id: "mn-16", label: "Run quarterly deep competitor analysis", priority: "must" },
      { id: "mn-17", label: "Reflect competitor strategy changes into your own strategy", priority: "must" },
      { id: "mn-18", label: "Note competitor wins / losses — where they moved ahead, where behind", priority: "should" },
      { id: "mn-19", label: "Set up monitoring tools — Semrush/Ahrefs alerts if available", priority: "should" },
      { id: "mn-20", label: "Share monitoring findings with client monthly", priority: "must" },
    ],
  },
  {
    id: "final-report",
    title: "Final Competitor Analysis Report",
    icon: "📋",
    description: "Analysis complete — now build an actionable report",
    checks: [
      { id: "fr-01", label: "Write executive summary — top 5 findings in bullet points", priority: "must" },
      { id: "fr-02", label: "Build competitor overview table — DA/traffic/keywords/backlinks", priority: "must" },
      { id: "fr-03", label: "Include keyword gap table — top opportunities", priority: "must" },
      { id: "fr-04", label: "Include content gap list — new pages needed", priority: "must" },
      { id: "fr-05", label: "Include backlink opportunities list — top 10", priority: "must" },
      { id: "fr-06", label: "Include SERP features opportunities", priority: "must" },
      { id: "fr-07", label: "Include competitor weaknesses section", priority: "must" },
      { id: "fr-08", label: "Include technical gaps section", priority: "must" },
      { id: "fr-09", label: "Recommendations — action items in priority order", priority: "must" },
      { id: "fr-10", label: "Separate quick wins (1-2 weeks) from long-term (3-6 months)", priority: "must" },
      { id: "fr-11", label: "Report is visually clean — tables, bullet points used", priority: "should" },
      { id: "fr-12", label: "Screenshots included where relevant", priority: "should" },
      { id: "fr-13", label: "Report written in client-friendly language — avoid technical jargon", priority: "should" },
      { id: "fr-14", label: "Next steps clearly defined", priority: "must" },
      { id: "fr-15", label: "Present report to client and gather feedback", priority: "must" },
    ],
  },
];

export const getCompTotalChecks = () =>
  competitorSopData.reduce((total, cat) => total + cat.checks.length, 0);

export const getCompCategoryProgress = (
  categoryId: string,
  checked: Record<string, boolean>
) => {
  const cat = competitorSopData.find((c) => c.id === categoryId);
  if (!cat) return { done: 0, total: 0 };
  const done = cat.checks.filter((ch) => checked[ch.id]).length;
  return { done, total: cat.checks.length };
};

export const getCompOverallProgress = (checked: Record<string, boolean>) => {
  const total = getCompTotalChecks();
  const done = Object.values(checked).filter(Boolean).length;
  return { done, total };
};
