export type IssueType = "issue" | "warning" | "opportunity";
export type Priority = "high" | "medium" | "low";

export interface SFIssue {
  id: string;
  label: string;
  type: IssueType;
  priority: Priority;
}

export interface SFCategory {
  id: string;
  label: string;
  description: string;
  issues: SFIssue[];
}

export const SF_CATEGORIES: SFCategory[] = [
  {
    id: "response_codes",
    label: "Response Codes",
    description: "HTTP response status codes — blocked URLs, no response, redirects, client/server errors.",
    issues: [
      { id: "rc_blocked_robots", label: "Blocked by Robots.txt", type: "issue", priority: "high" },
      { id: "rc_no_response", label: "No Response", type: "issue", priority: "high" },
      { id: "rc_blocked_resource", label: "Blocked Resource", type: "issue", priority: "high" },
      { id: "rc_404", label: "404 Not Found", type: "issue", priority: "high" },
      { id: "rc_5xx", label: "5XX Server Error", type: "issue", priority: "high" },
      { id: "rc_4xx", label: "4XX Client Error", type: "issue", priority: "high" },
      { id: "rc_redirect_chain", label: "Redirect Chain", type: "issue", priority: "medium" },
      { id: "rc_redirect_loop", label: "Redirect Loop", type: "issue", priority: "high" },
      { id: "rc_301", label: "301 Moved Permanently", type: "warning", priority: "medium" },
      { id: "rc_302", label: "302 Found (Temporary Redirect)", type: "warning", priority: "medium" },
      { id: "rc_meta_refresh", label: "Meta Refresh Redirect", type: "warning", priority: "medium" },
      { id: "rc_js_redirect", label: "JavaScript Redirect", type: "warning", priority: "low" },
      { id: "rc_3xx", label: "3XX Redirect", type: "warning", priority: "low" },
    ],
  },
  {
    id: "security",
    label: "Security",
    description: "Basic security best practices — HTTPS, mixed content, HTTP security headers.",
    issues: [
      { id: "sec_http", label: "HTTP Page (Not HTTPS)", type: "issue", priority: "high" },
      { id: "sec_mixed_content", label: "Contains Mixed Content", type: "issue", priority: "high" },
      { id: "sec_missing_hsts", label: "Missing HSTS Header", type: "warning", priority: "medium" },
      { id: "sec_missing_csp", label: "Missing Content-Security-Policy Header", type: "warning", priority: "medium" },
      { id: "sec_missing_xframe", label: "Missing X-Frame-Options Header", type: "warning", priority: "medium" },
      { id: "sec_missing_xcontent", label: "Missing X-Content-Type-Options Header", type: "warning", priority: "low" },
      { id: "sec_missing_referrer", label: "Missing Referrer-Policy Header", type: "warning", priority: "low" },
      { id: "sec_missing_permissions", label: "Missing Permissions-Policy Header", type: "warning", priority: "low" },
      { id: "sec_http_internal", label: "HTTP Internal Link on HTTPS Page", type: "issue", priority: "high" },
    ],
  },
  {
    id: "url",
    label: "URL",
    description: "Logical and relevant URLs — non-optimal formats, discoverable URLs that shouldn't be.",
    issues: [
      { id: "url_uppercase", label: "Uppercase in URL", type: "issue", priority: "medium" },
      { id: "url_underscores", label: "Underscores in URL", type: "issue", priority: "medium" },
      { id: "url_spaces", label: "Spaces in URL", type: "issue", priority: "high" },
      { id: "url_special_chars", label: "Special Characters in URL", type: "issue", priority: "medium" },
      { id: "url_over_115", label: "URL Over 115 Characters", type: "issue", priority: "medium" },
      { id: "url_duplicate_slash", label: "Duplicate Slashes in URL", type: "issue", priority: "medium" },
      { id: "url_params", label: "URL Contains Parameters", type: "warning", priority: "low" },
      { id: "url_session_id", label: "URL Contains Session ID", type: "issue", priority: "high" },
      { id: "url_dynamic", label: "Dynamically Generated URL", type: "warning", priority: "low" },
      { id: "url_non_ascii", label: "Non-ASCII Characters in URL", type: "warning", priority: "medium" },
      { id: "url_missing_trailing_slash", label: "Missing Trailing Slash", type: "warning", priority: "low" },
      { id: "url_too_deep", label: "URL Too Deep (4+ subdirectories)", type: "warning", priority: "medium" },
      { id: "url_short_word", label: "Short URL — Less Than 5 Characters", type: "opportunity", priority: "low" },
      { id: "url_www_non_www", label: "www / Non-www Inconsistency", type: "issue", priority: "high" },
    ],
  },
  {
    id: "page_titles",
    label: "Page Titles",
    description: "Relevant and descriptive page titles for users and search engines.",
    issues: [
      { id: "pt_missing", label: "Missing Title Tag", type: "issue", priority: "high" },
      { id: "pt_duplicate", label: "Duplicate Title Tag", type: "issue", priority: "high" },
      { id: "pt_too_long", label: "Title Tag Over 60 Characters", type: "issue", priority: "medium" },
      { id: "pt_too_short", label: "Title Tag Below 30 Characters", type: "opportunity", priority: "medium" },
      { id: "pt_multiple", label: "Multiple Title Tags", type: "issue", priority: "high" },
      { id: "pt_same_h1", label: "Title Tag Same as H1", type: "opportunity", priority: "low" },
      { id: "pt_no_keyword", label: "Title Tag Doesn't Contain Target Keyword", type: "opportunity", priority: "high" },
      { id: "pt_boilerplate", label: "Boilerplate / Templated Title", type: "opportunity", priority: "medium" },
      { id: "pt_over_568px", label: "Title Tag Over 568px Width", type: "issue", priority: "medium" },
    ],
  },
  {
    id: "meta_description",
    label: "Meta Description",
    description: "Meta descriptions used in search snippets — drive clicks to website.",
    issues: [
      { id: "md_missing", label: "Missing Meta Description", type: "issue", priority: "high" },
      { id: "md_duplicate", label: "Duplicate Meta Description", type: "issue", priority: "high" },
      { id: "md_too_long", label: "Meta Description Over 155 Characters", type: "issue", priority: "medium" },
      { id: "md_too_short", label: "Meta Description Below 70 Characters", type: "opportunity", priority: "medium" },
      { id: "md_multiple", label: "Multiple Meta Descriptions", type: "issue", priority: "high" },
      { id: "md_no_keyword", label: "Meta Description Doesn't Contain Target Keyword", type: "opportunity", priority: "medium" },
      { id: "md_over_990px", label: "Meta Description Over 990px Width", type: "issue", priority: "medium" },
    ],
  },
  {
    id: "h1",
    label: "H1",
    description: "H1 heading — describes the main title and purpose of the page.",
    issues: [
      { id: "h1_missing", label: "Missing H1 Tag", type: "issue", priority: "high" },
      { id: "h1_duplicate", label: "Duplicate H1 Tag", type: "issue", priority: "medium" },
      { id: "h1_too_long", label: "H1 Over 70 Characters", type: "issue", priority: "medium" },
      { id: "h1_multiple", label: "Multiple H1 Tags", type: "warning", priority: "medium" },
      { id: "h1_same_title", label: "H1 Same as Title Tag", type: "opportunity", priority: "low" },
      { id: "h1_no_keyword", label: "H1 Doesn't Contain Target Keyword", type: "opportunity", priority: "high" },
      { id: "h1_non_sequential", label: "Non-Sequential H1 (skipped heading levels)", type: "warning", priority: "low" },
    ],
  },
  {
    id: "h2",
    label: "H2",
    description: "H2 headings — section descriptions and signposts within page content.",
    issues: [
      { id: "h2_missing", label: "Missing H2 Tag", type: "warning", priority: "low" },
      { id: "h2_duplicate", label: "Duplicate H2 Tag", type: "warning", priority: "low" },
      { id: "h2_too_long", label: "H2 Over 70 Characters", type: "warning", priority: "low" },
      { id: "h2_multiple_same", label: "Multiple Identical H2 Tags", type: "warning", priority: "medium" },
      { id: "h2_non_sequential", label: "Non-Sequential H2 (skipped heading levels)", type: "warning", priority: "low" },
      { id: "h2_no_keyword", label: "H2 Doesn't Contain Target Keyword", type: "opportunity", priority: "medium" },
    ],
  },
  {
    id: "content",
    label: "Content",
    description: "On-page content quality — duplicates, low content, readability.",
    issues: [
      { id: "ct_exact_duplicate", label: "Exact Duplicate Content", type: "issue", priority: "high" },
      { id: "ct_near_duplicate", label: "Near Duplicate Content", type: "issue", priority: "high" },
      { id: "ct_low_content", label: "Low Content / Thin Page (< 200 words)", type: "issue", priority: "high" },
      { id: "ct_no_content", label: "No Content on Page", type: "issue", priority: "high" },
      { id: "ct_spell_errors", label: "Spelling Errors Detected", type: "warning", priority: "medium" },
      { id: "ct_grammar_errors", label: "Grammar Errors Detected", type: "warning", priority: "medium" },
      { id: "ct_low_readability", label: "Low Readability Score", type: "opportunity", priority: "medium" },
      { id: "ct_no_target_keyword", label: "Target Keyword Not Found in Content", type: "opportunity", priority: "high" },
      { id: "ct_keyword_stuffing", label: "Keyword Stuffing Detected", type: "issue", priority: "high" },
      { id: "ct_outdated", label: "Outdated Content (dates/info)", type: "opportunity", priority: "medium" },
      { id: "ct_no_structured", label: "No Structured Formatting (bullets, headings)", type: "opportunity", priority: "low" },
    ],
  },
  {
    id: "images",
    label: "Images",
    description: "Imagery issues — large images, missing alt text, incorrectly sized images, CLS.",
    issues: [
      { id: "img_missing_alt", label: "Missing Alt Text", type: "issue", priority: "high" },
      { id: "img_empty_alt", label: "Empty Alt Text", type: "warning", priority: "medium" },
      { id: "img_alt_too_long", label: "Alt Text Over 100 Characters", type: "warning", priority: "low" },
      { id: "img_large_file", label: "Image File Size Over 100KB", type: "issue", priority: "high" },
      { id: "img_no_dimensions", label: "Images Without Width/Height Attributes", type: "issue", priority: "medium" },
      { id: "img_wrong_size", label: "Image Incorrectly Sized", type: "warning", priority: "medium" },
      { id: "img_broken", label: "Broken Image (404)", type: "issue", priority: "high" },
      { id: "img_cls", label: "Cumulative Layout Shift (CLS) Caused by Image", type: "issue", priority: "high" },
      { id: "img_no_webp", label: "Image Not in Next-Gen Format (WebP/AVIF)", type: "opportunity", priority: "medium" },
      { id: "img_no_lazy", label: "Images Not Lazy Loaded", type: "opportunity", priority: "medium" },
      { id: "img_svg_not_inline", label: "SVG Not Inline (missed optimisation)", type: "opportunity", priority: "low" },
    ],
  },
  {
    id: "canonicals",
    label: "Canonicals",
    description: "Rel=canonical — duplicate content, which URL should be indexed.",
    issues: [
      { id: "can_missing", label: "Missing Canonical Tag", type: "issue", priority: "medium" },
      { id: "can_canonicalised", label: "Canonicalised Page (not self-referencing)", type: "warning", priority: "medium" },
      { id: "can_non_indexable", label: "Non-Indexable Canonical", type: "issue", priority: "high" },
      { id: "can_multiple", label: "Multiple Canonical Tags", type: "issue", priority: "high" },
      { id: "can_relative", label: "Relative Canonical URL", type: "warning", priority: "medium" },
      { id: "can_different_domain", label: "Canonical to Different Domain", type: "warning", priority: "high" },
      { id: "can_no_follow", label: "Canonical Not Followed", type: "issue", priority: "high" },
      { id: "can_404", label: "Canonical Points to 404 Page", type: "issue", priority: "high" },
      { id: "can_inconsistent", label: "Inconsistent Canonicalisation", type: "issue", priority: "high" },
      { id: "can_www_non_www", label: "Canonical www / Non-www Inconsistency", type: "issue", priority: "high" },
    ],
  },
  {
    id: "pagination",
    label: "Pagination",
    description: "Pagination setup — non-200 response URLs, non-indexable paginated pages, sequence issues.",
    issues: [
      { id: "pag_non_200", label: "Non-200 Response URL in Pagination", type: "issue", priority: "high" },
      { id: "pag_non_indexable", label: "Non-Indexable Paginated Page", type: "issue", priority: "medium" },
      { id: "pag_missing_rel", label: "Missing rel=next/prev", type: "warning", priority: "medium" },
      { id: "pag_broken_seq", label: "Broken Pagination Sequence", type: "issue", priority: "high" },
      { id: "pag_self_ref_missing", label: "Paginated Page Missing Self-Referencing Canonical", type: "warning", priority: "medium" },
      { id: "pag_noindex", label: "Paginated Page Contains Noindex", type: "warning", priority: "medium" },
    ],
  },
  {
    id: "directives",
    label: "Directives",
    description: "Robots meta tag and X-Robots-Tag — noindex, nofollow, none directives.",
    issues: [
      { id: "dir_noindex", label: "Noindex in Meta Robots", type: "issue", priority: "high" },
      { id: "dir_noindex_header", label: "Noindex in X-Robots-Tag Header", type: "issue", priority: "high" },
      { id: "dir_nofollow_page", label: "Nofollow in Meta Robots (Page Level)", type: "warning", priority: "medium" },
      { id: "dir_none", label: "None Directive (Noindex + Nofollow)", type: "issue", priority: "high" },
      { id: "dir_noarchive", label: "Noarchive Directive", type: "warning", priority: "low" },
      { id: "dir_nosnippet", label: "Nosnippet Directive", type: "warning", priority: "medium" },
      { id: "dir_conflict", label: "Conflicting Directives (robots.txt vs meta robots)", type: "issue", priority: "high" },
      { id: "dir_indexable_noindex", label: "Indexable Page with Noindex (mismatch)", type: "issue", priority: "high" },
    ],
  },
  {
    id: "hreflang",
    label: "Hreflang",
    description: "Multiple language/region page versions — return links, language codes.",
    issues: [
      { id: "hre_non_200", label: "Non-200 URL in Hreflang", type: "issue", priority: "high" },
      { id: "hre_missing_return", label: "Missing Return Link in Hreflang", type: "issue", priority: "high" },
      { id: "hre_invalid_lang", label: "Invalid Language Code in Hreflang", type: "issue", priority: "high" },
      { id: "hre_invalid_region", label: "Invalid Region Code in Hreflang", type: "issue", priority: "high" },
      { id: "hre_multiple_xdefault", label: "Multiple x-default Hreflang", type: "issue", priority: "high" },
      { id: "hre_missing_self", label: "Hreflang Missing Self Reference", type: "warning", priority: "medium" },
      { id: "hre_non_canonical", label: "Hreflang to Non-Canonical URL", type: "warning", priority: "medium" },
      { id: "hre_noindex", label: "Hreflang to Noindex URL", type: "issue", priority: "high" },
      { id: "hre_inconsistent", label: "Inconsistent Hreflang Implementation", type: "warning", priority: "medium" },
    ],
  },
  {
    id: "javascript",
    label: "JavaScript",
    description: "JS rendering issues — blocked resources, JS content and links, key elements.",
    issues: [
      { id: "js_blocked", label: "JavaScript Blocked by Robots.txt", type: "issue", priority: "high" },
      { id: "js_links_not_crawlable", label: "JavaScript Links Not Crawlable", type: "issue", priority: "high" },
      { id: "js_content_not_rendered", label: "Key Content Not Rendered (JS dependent)", type: "issue", priority: "high" },
      { id: "js_css_blocked", label: "CSS Blocked by Robots.txt", type: "warning", priority: "medium" },
      { id: "js_render_diff", label: "Significant Difference Between Crawl and Rendered HTML", type: "warning", priority: "high" },
      { id: "js_console_errors", label: "JavaScript Console Errors", type: "warning", priority: "medium" },
      { id: "js_slow_render", label: "Slow JavaScript Rendering", type: "warning", priority: "medium" },
    ],
  },
  {
    id: "links",
    label: "Links",
    description: "Internal and external links — crawl depth, non-descriptive anchors, broken links.",
    issues: [
      { id: "lnk_broken_internal", label: "Broken Internal Link (404)", type: "issue", priority: "high" },
      { id: "lnk_broken_external", label: "Broken External Link (404)", type: "issue", priority: "medium" },
      { id: "lnk_high_crawl_depth", label: "Page With High Crawl Depth (4+ clicks)", type: "issue", priority: "medium" },
      { id: "lnk_no_internal_outlinks", label: "No Internal Outlinks on Page", type: "issue", priority: "medium" },
      { id: "lnk_non_descriptive", label: "Non-Descriptive Anchor Text (click here, etc.)", type: "issue", priority: "medium" },
      { id: "lnk_nofollow_internal", label: "Nofollow Internal Link", type: "warning", priority: "medium" },
      { id: "lnk_orphan", label: "Orphan Page (No Internal Links Pointing To It)", type: "issue", priority: "high" },
      { id: "lnk_redirect_link", label: "Internal Link Pointing to Redirect", type: "warning", priority: "medium" },
      { id: "lnk_external_nofollow", label: "External Link Without Nofollow/Sponsored/UGC", type: "opportunity", priority: "low" },
      { id: "lnk_too_many", label: "Too Many Internal Links on Page (>100)", type: "warning", priority: "low" },
      { id: "lnk_nav_not_crawlable", label: "Navigation Not Crawlable", type: "issue", priority: "high" },
      { id: "lnk_low_internal", label: "Low Number of Internal Links (< 3)", type: "opportunity", priority: "medium" },
    ],
  },
  {
    id: "amp",
    label: "AMP",
    description: "AMP HTML framework — fast-loading mobile pages, AMP specifications.",
    issues: [
      { id: "amp_invalid", label: "Invalid AMP Page (AMP Validator Error)", type: "issue", priority: "high" },
      { id: "amp_missing_canonical", label: "AMP Missing Canonical to HTML Version", type: "issue", priority: "high" },
      { id: "amp_missing_amphtml", label: "HTML Page Missing rel=amphtml Link", type: "warning", priority: "medium" },
      { id: "amp_noindex", label: "AMP Page is Noindex", type: "issue", priority: "high" },
      { id: "amp_blocked", label: "AMP Page Blocked by Robots.txt", type: "issue", priority: "high" },
      { id: "amp_non_200", label: "AMP Page Returns Non-200 Response", type: "issue", priority: "high" },
    ],
  },
  {
    id: "structured_data",
    label: "Structured Data",
    description: "Schema.org — rich results, Google's feature requirements.",
    issues: [
      { id: "sd_invalid", label: "Invalid Structured Data (Schema.org Error)", type: "issue", priority: "high" },
      { id: "sd_missing", label: "Missing Structured Data (Recommended Type)", type: "opportunity", priority: "medium" },
      { id: "sd_parse_error", label: "Structured Data Parse Error", type: "issue", priority: "high" },
      { id: "sd_missing_required", label: "Missing Required Schema Property", type: "issue", priority: "high" },
      { id: "sd_missing_recommended", label: "Missing Recommended Schema Property", type: "opportunity", priority: "medium" },
      { id: "sd_breadcrumb_missing", label: "Missing Breadcrumb Structured Data", type: "opportunity", priority: "low" },
      { id: "sd_faq_missing", label: "Missing FAQ Structured Data on FAQ Page", type: "opportunity", priority: "medium" },
      { id: "sd_product_missing", label: "Missing Product Structured Data on Product Page", type: "opportunity", priority: "high" },
      { id: "sd_review_missing", label: "Missing Review/Rating Structured Data", type: "opportunity", priority: "medium" },
      { id: "sd_org_missing", label: "Missing Organisation Structured Data on Homepage", type: "opportunity", priority: "medium" },
    ],
  },
  {
    id: "sitemaps",
    label: "Sitemaps",
    description: "XML Sitemaps — up to date, error free, indexable canonical URLs.",
    issues: [
      { id: "sm_not_in_sitemap", label: "Indexable Page Not in XML Sitemap", type: "issue", priority: "high" },
      { id: "sm_orphan", label: "Orphan URL in Sitemap (No Internal Links)", type: "warning", priority: "medium" },
      { id: "sm_noindex_in_sitemap", label: "Noindex URL in Sitemap", type: "issue", priority: "high" },
      { id: "sm_redirect_in_sitemap", label: "Redirect URL in Sitemap", type: "issue", priority: "medium" },
      { id: "sm_404_in_sitemap", label: "404 URL in Sitemap", type: "issue", priority: "high" },
      { id: "sm_non_canonical", label: "Non-Canonical URL in Sitemap", type: "issue", priority: "medium" },
      { id: "sm_missing", label: "No XML Sitemap Found", type: "issue", priority: "high" },
      { id: "sm_not_submitted", label: "Sitemap Not Submitted to Search Console", type: "warning", priority: "medium" },
      { id: "sm_too_large", label: "Sitemap Over 50MB / 50,000 URLs", type: "issue", priority: "high" },
      { id: "sm_not_in_robots", label: "Sitemap Not Referenced in robots.txt", type: "warning", priority: "low" },
      { id: "sm_incorrect_date", label: "Incorrect Last Modified Date", type: "warning", priority: "low" },
      { id: "sm_blocked", label: "Sitemap Blocked by robots.txt", type: "issue", priority: "high" },
    ],
  },
  {
    id: "pagespeed",
    label: "PageSpeed",
    description: "PageSpeed Insights — render-blocking, large images, compression, Core Web Vitals.",
    issues: [
      { id: "ps_lcp_poor", label: "Poor LCP (Largest Contentful Paint > 4s)", type: "issue", priority: "high" },
      { id: "ps_fid_poor", label: "Poor FID / INP (Interaction > 300ms)", type: "issue", priority: "high" },
      { id: "ps_cls_poor", label: "Poor CLS (Cumulative Layout Shift > 0.25)", type: "issue", priority: "high" },
      { id: "ps_render_blocking", label: "Render-Blocking Resources", type: "opportunity", priority: "high" },
      { id: "ps_unused_css", label: "Unused CSS", type: "opportunity", priority: "medium" },
      { id: "ps_unused_js", label: "Unused JavaScript", type: "opportunity", priority: "medium" },
      { id: "ps_no_compression", label: "No Text Compression (Gzip/Brotli)", type: "opportunity", priority: "high" },
      { id: "ps_no_caching", label: "Serve Static Assets Without Cache Policy", type: "opportunity", priority: "medium" },
      { id: "ps_large_dom", label: "Excessive DOM Size (>1500 nodes)", type: "opportunity", priority: "medium" },
      { id: "ps_no_preconnect", label: "Missing Preconnect / DNS-Prefetch", type: "opportunity", priority: "low" },
      { id: "ps_third_party", label: "Third-Party Code Blocking Main Thread", type: "opportunity", priority: "medium" },
      { id: "ps_ttfb_slow", label: "Slow Time to First Byte (TTFB > 600ms)", type: "issue", priority: "high" },
    ],
  },
  {
    id: "mobile",
    label: "Mobile",
    description: "Mobile usability — viewport, tap targets, content sizing.",
    issues: [
      { id: "mob_no_viewport", label: "Missing Viewport Meta Tag", type: "issue", priority: "high" },
      { id: "mob_small_tap", label: "Tap Targets Too Small (< 48px)", type: "issue", priority: "medium" },
      { id: "mob_content_wider", label: "Content Wider Than Screen", type: "issue", priority: "high" },
      { id: "mob_font_small", label: "Text Too Small to Read (< 12px)", type: "warning", priority: "medium" },
      { id: "mob_not_mobile_friendly", label: "Page Not Mobile-Friendly (Lighthouse)", type: "issue", priority: "high" },
      { id: "mob_fixed_width", label: "Fixed Width Viewport", type: "issue", priority: "high" },
      { id: "mob_interstitial", label: "Intrusive Interstitial on Mobile", type: "issue", priority: "high" },
    ],
  },
  {
    id: "accessibility",
    label: "Accessibility",
    description: "Inclusive and user-friendly — disabilities, AXE engine findings.",
    issues: [
      { id: "acc_missing_lang", label: "Missing HTML lang Attribute", type: "warning", priority: "medium" },
      { id: "acc_color_contrast", label: "Insufficient Color Contrast Ratio", type: "warning", priority: "medium" },
      { id: "acc_no_form_label", label: "Form Input Missing Label", type: "warning", priority: "high" },
      { id: "acc_missing_aria", label: "Missing ARIA Attributes", type: "warning", priority: "medium" },
      { id: "acc_missing_skip", label: "Missing Skip Navigation Link", type: "warning", priority: "low" },
      { id: "acc_img_missing_alt", label: "Image Missing Alt (Accessibility)", type: "warning", priority: "high" },
      { id: "acc_keyboard", label: "Keyboard Navigation Issue", type: "warning", priority: "high" },
      { id: "acc_empty_button", label: "Button Without Accessible Name", type: "warning", priority: "medium" },
      { id: "acc_empty_link", label: "Empty Link (No Anchor Text)", type: "warning", priority: "medium" },
      { id: "acc_heading_order", label: "Heading Order Not Logical", type: "warning", priority: "low" },
    ],
  },
  {
    id: "analytics",
    label: "Analytics",
    description: "Google Analytics — orphan URLs, non-indexable URLs with GA data.",
    issues: [
      { id: "ana_orphan", label: "Orphan URL Found in Analytics (No Internal Links)", type: "issue", priority: "high" },
      { id: "ana_noindex_traffic", label: "Non-Indexable Page Receiving Organic Traffic", type: "issue", priority: "high" },
      { id: "ana_not_tracked", label: "Page Not Tracked in Analytics", type: "warning", priority: "medium" },
      { id: "ana_ga_missing", label: "Google Analytics Code Missing", type: "issue", priority: "high" },
      { id: "ana_duplicate_ga", label: "Duplicate Google Analytics Code", type: "issue", priority: "high" },
      { id: "ana_no_events", label: "No Goal / Event Tracking Setup", type: "warning", priority: "medium" },
    ],
  },
  {
    id: "search_console",
    label: "Search Console",
    description: "Google Search Console — click data, indexing, orphan URLs.",
    issues: [
      { id: "sc_orphan", label: "Orphan URL Found in Search Console", type: "issue", priority: "high" },
      { id: "sc_no_search_data", label: "URL Without Search Analytics Data (Impressions)", type: "warning", priority: "medium" },
      { id: "sc_not_indexed", label: "URL Submitted But Not Indexed", type: "issue", priority: "high" },
      { id: "sc_coverage_error", label: "Coverage Error in Search Console", type: "issue", priority: "high" },
      { id: "sc_excluded", label: "URL Excluded From Index (needs review)", type: "warning", priority: "medium" },
      { id: "sc_manual_action", label: "Manual Action Penalty", type: "issue", priority: "high" },
      { id: "sc_core_vitals_fail", label: "Core Web Vitals Failing in Search Console", type: "issue", priority: "high" },
      { id: "sc_mobile_usability", label: "Mobile Usability Errors in Search Console", type: "issue", priority: "high" },
    ],
  },
  {
    id: "validation",
    label: "Validation",
    description: "Valid HTML — helps crawlers parse and understand pages accurately.",
    issues: [
      { id: "val_html_errors", label: "HTML Validation Errors (W3C)", type: "issue", priority: "medium" },
      { id: "val_html_warnings", label: "HTML Validation Warnings (W3C)", type: "warning", priority: "low" },
      { id: "val_unclosed_tags", label: "Unclosed HTML Tags", type: "issue", priority: "high" },
      { id: "val_deprecated_tags", label: "Deprecated HTML Tags Used", type: "warning", priority: "low" },
      { id: "val_duplicate_ids", label: "Duplicate ID Attributes", type: "issue", priority: "medium" },
      { id: "val_invalid_schema", label: "Invalid HTML Schema Markup", type: "issue", priority: "medium" },
      { id: "val_doctype", label: "Missing or Incorrect DOCTYPE", type: "issue", priority: "medium" },
      { id: "val_charset", label: "Missing Charset Declaration", type: "issue", priority: "medium" },
      { id: "val_opportunity", label: "HTML Optimisation Opportunities", type: "opportunity", priority: "low" },
    ],
  },
];

export const ALL_CATEGORIES_MAP = Object.fromEntries(SF_CATEGORIES.map((c) => [c.id, c]));

export function getTotalIssueCount() {
  return SF_CATEGORIES.reduce((sum, cat) => sum + cat.issues.length, 0);
}

export function getIssuesByType(type: IssueType) {
  return SF_CATEGORIES.flatMap((cat) => cat.issues.filter((i) => i.type === type));
}
