export interface SopCheck {
  id: string;
  label: string;
  detail?: string;
  priority: "high" | "medium" | "low";
}

export interface SopCategory {
  id: string;
  title: string;
  icon: string;
  checks: SopCheck[];
}

export const seoSopData: SopCategory[] = [
  {
    id: "keyword-research",
    title: "Keyword Research",
    icon: "🔍",
    checks: [
      { id: "kw-01", label: "Identify seed keyword — what is the main topic", priority: "high" },
      { id: "kw-02", label: "Confirm primary keyword (1 main keyword per page)", priority: "high" },
      { id: "kw-03", label: "List secondary keywords (3-5)", priority: "high" },
      { id: "kw-04", label: "Find long-tail variations (question-based)", priority: "high" },
      { id: "kw-05", label: "Check monthly search volume", priority: "high" },
      { id: "kw-06", label: "Check keyword difficulty (KD)", priority: "high" },
      { id: "kw-07", label: "Check CPC value (commercial intent signal)", priority: "medium" },
      { id: "kw-08", label: "Check SERP volatility", priority: "medium" },
      { id: "kw-09", label: "Note related keywords", priority: "medium" },
      { id: "kw-10", label: "Check Google Autocomplete suggestions", priority: "medium" },
      { id: "kw-11", label: "List People Also Ask (PAA) questions (min 5)", priority: "high" },
      { id: "kw-12", label: "Note People Also Search For (PASF) terms", priority: "medium" },
      { id: "kw-13", label: "Check keyword cannibalization — no existing page ranking for same keyword", priority: "high" },
      { id: "kw-14", label: "Check geo-modified keywords (city/country + keyword)", priority: "medium" },
      { id: "kw-15", label: "Check seasonal trends (Google Trends)", priority: "low" },
      { id: "kw-16", label: "Identify brand vs non-brand keywords", priority: "medium" },
      { id: "kw-17", label: "List informational keywords", priority: "medium" },
      { id: "kw-18", label: "List commercial keywords", priority: "high" },
      { id: "kw-19", label: "List transactional keywords", priority: "high" },
      { id: "kw-20", label: "Identify navigational keywords", priority: "low" },
      { id: "kw-21", label: "Compile question keywords (who/what/where/when/why/how)", priority: "high" },
      { id: "kw-22", label: "Check comparison keywords (X vs Y)", priority: "medium" },
      { id: "kw-23", label: "Check best/top keywords", priority: "medium" },
      { id: "kw-24", label: "Check 'near me' keywords (local intent)", priority: "medium" },
      { id: "kw-25", label: "Check featured snippet opportunity", priority: "high" },
      { id: "kw-26", label: "Identify video intent keywords", priority: "low" },
      { id: "kw-27", label: "Identify image search keywords", priority: "low" },
      { id: "kw-28", label: "Cluster keywords — group related terms together", priority: "high" },
      { id: "kw-29", label: "Identify parent topic (broader category)", priority: "medium" },
      { id: "kw-30", label: "Identify sub-topic keywords", priority: "medium" },
      { id: "kw-31", label: "Note synonym keywords", priority: "medium" },
      { id: "kw-32", label: "Check abbreviations / acronyms", priority: "low" },
      { id: "kw-33", label: "Check misspelling variants", priority: "low" },
      { id: "kw-34", label: "Match keyword intent with page type", priority: "high" },
      { id: "kw-35", label: "Decide exact match vs broad match", priority: "medium" },
      { id: "kw-36", label: "Identify negative keywords (ones not to target)", priority: "low" },
      { id: "kw-37", label: "Set keyword priority order", priority: "medium" },
      { id: "kw-38", label: "Check short-tail vs long-tail balance", priority: "medium" },
      { id: "kw-39", label: "Hand final keyword map to writer", priority: "high" },
      { id: "kw-40", label: "Create keyword placement plan (H1/H2/body/meta)", priority: "high" },
    ],
  },
  {
    id: "competitor-research",
    title: "Competitor Research",
    icon: "🏆",
    checks: [
      { id: "cr-01", label: "Note top 5 SERP results for main keyword", priority: "high" },
      { id: "cr-02", label: "Identify top 3 direct competitors", priority: "high" },
      { id: "cr-03", label: "Competitor #1 — note URL", priority: "high" },
      { id: "cr-04", label: "Competitor #1 — copy title tag", priority: "high" },
      { id: "cr-05", label: "Competitor #1 — check word count", priority: "high" },
      { id: "cr-06", label: "Competitor #1 — list H1, H2s", priority: "high" },
      { id: "cr-07", label: "Competitor #1 — note content format (guide/list/comparison)", priority: "medium" },
      { id: "cr-08", label: "Competitor #1 — note all sections covered", priority: "high" },
      { id: "cr-09", label: "Competitor #1 — note images / media used", priority: "medium" },
      { id: "cr-10", label: "Competitor #1 — check schema markup", priority: "medium" },
      { id: "cr-11", label: "Competitor #2 — note URL", priority: "high" },
      { id: "cr-12", label: "Competitor #2 — copy title tag", priority: "high" },
      { id: "cr-13", label: "Competitor #2 — check word count", priority: "high" },
      { id: "cr-14", label: "Competitor #2 — list H1, H2s", priority: "high" },
      { id: "cr-15", label: "Competitor #2 — note content format", priority: "medium" },
      { id: "cr-16", label: "Competitor #2 — note all sections covered", priority: "high" },
      { id: "cr-17", label: "Competitor #3 — note URL", priority: "high" },
      { id: "cr-18", label: "Competitor #3 — check word count", priority: "high" },
      { id: "cr-19", label: "Competitor #3 — list H1, H2s", priority: "high" },
      { id: "cr-20", label: "Competitor #3 — note sections covered", priority: "high" },
      { id: "cr-21", label: "Calculate average competitor word count", priority: "high" },
      { id: "cr-22", label: "Identify content gap — what competitors did not cover", priority: "high" },
      { id: "cr-23", label: "Identify common sections — what all covered (must-have)", priority: "high" },
      { id: "cr-24", label: "Find unique angle — your differentiation point", priority: "high" },
      { id: "cr-25", label: "Check competitor backlink sources", priority: "medium" },
      { id: "cr-26", label: "Note competitor Domain Authority (DA)", priority: "medium" },
      { id: "cr-27", label: "Note who owns the featured snippet", priority: "high" },
      { id: "cr-28", label: "Note which content appears in PAA answers", priority: "medium" },
      { id: "cr-29", label: "Note competitor tone / style (formal/casual)", priority: "medium" },
      { id: "cr-30", label: "Note competitor CTAs", priority: "medium" },
      { id: "cr-31", label: "Review competitor internal linking structure", priority: "medium" },
      { id: "cr-32", label: "Check competitor publish date (content freshness)", priority: "low" },
      { id: "cr-33", label: "Check competitor update frequency", priority: "low" },
      { id: "cr-34", label: "Check social signals (shares/comments)", priority: "low" },
      { id: "cr-35", label: "Note competitor FAQ sections", priority: "medium" },
      { id: "cr-36", label: "Are competitors using video content?", priority: "low" },
      { id: "cr-37", label: "Note infographics / visual content used", priority: "low" },
      { id: "cr-38", label: "Is any competitor providing outdated info? (opportunity)", priority: "high" },
      { id: "cr-39", label: "Is any competitor providing thin content? (opportunity)", priority: "high" },
      { id: "cr-40", label: "Hand final competitor summary to writer", priority: "high" },
      { id: "cr-41", label: "Check competitor keyword overlap", priority: "medium" },
      { id: "cr-42", label: "Note competitor meta descriptions", priority: "low" },
      { id: "cr-43", label: "Note competitor URL structure", priority: "low" },
      { id: "cr-44", label: "Are competitors using tables / comparisons?", priority: "medium" },
      { id: "cr-45", label: "Are competitors using expert quotes / statistics?", priority: "medium" },
      { id: "cr-46", label: "Are competitors using case studies / examples?", priority: "medium" },
      { id: "cr-47", label: "Are competitors using reviews / testimonials?", priority: "medium" },
      { id: "cr-48", label: "Note trust signals (certifications, awards)", priority: "medium" },
      { id: "cr-49", label: "Note readability level (simple vs complex)", priority: "low" },
      { id: "cr-50", label: "Check competitor mobile experience", priority: "low" },
    ],
  },
  {
    id: "search-intent",
    title: "Search Intent & SERP Analysis",
    icon: "🎯",
    checks: [
      { id: "si-01", label: "Identify search intent — Informational/Navigational/Commercial/Transactional", priority: "high" },
      { id: "si-02", label: "Note SERP result types — articles/products/local pack/videos", priority: "high" },
      { id: "si-03", label: "Is featured snippet present? Note format (paragraph/list/table)", priority: "high" },
      { id: "si-04", label: "Optimize content to capture featured snippet", priority: "high" },
      { id: "si-05", label: "List People Also Ask (PAA) questions (min 5)", priority: "high" },
      { id: "si-06", label: "Answer PAA questions within content", priority: "high" },
      { id: "si-07", label: "Is local pack present in SERP?", priority: "medium" },
      { id: "si-08", label: "Is image pack present?", priority: "low" },
      { id: "si-09", label: "Is video carousel present?", priority: "low" },
      { id: "si-10", label: "Are shopping results present?", priority: "low" },
      { id: "si-11", label: "Is knowledge panel present?", priority: "low" },
      { id: "si-12", label: "Clearly understand what the user is actually looking for", priority: "high" },
      { id: "si-13", label: "Match content format to intent", priority: "high" },
      { id: "si-14", label: "Match content depth to intent", priority: "high" },
      { id: "si-15", label: "Match content angle (beginner/expert/quick answer)", priority: "high" },
      { id: "si-16", label: "Identify funnel stage (awareness/consideration/decision)", priority: "medium" },
      { id: "si-17", label: "Set CTA according to funnel stage", priority: "medium" },
      { id: "si-18", label: "Note related searches (bottom of SERP)", priority: "medium" },
      { id: "si-19", label: "Identify SERP features opportunities", priority: "medium" },
      { id: "si-20", label: "Check zero-click search opportunity", priority: "medium" },
      { id: "si-21", label: "Check voice search intent (conversational queries)", priority: "medium" },
      { id: "si-22", label: "Check mobile vs desktop SERP differences", priority: "low" },
      { id: "si-23", label: "Identify local vs global intent", priority: "medium" },
      { id: "si-24", label: "Check seasonal intent", priority: "low" },
      { id: "si-25", label: "Identify micro-moments (I-want-to-know/go/do/buy)", priority: "medium" },
      { id: "si-26", label: "Check content freshness requirement (evergreen vs timely)", priority: "medium" },
      { id: "si-27", label: "Handle multi-intent keywords", priority: "medium" },
      { id: "si-28", label: "Satisfy intent above the fold", priority: "high" },
      { id: "si-29", label: "Assess bounce rate risk — is intent clearly satisfied?", priority: "high" },
      { id: "si-30", label: "Optimize dwell time — engaging content", priority: "medium" },
      { id: "si-31", label: "Optimize CTR — compelling title/meta", priority: "high" },
      { id: "si-32", label: "Check SERP snippet preview", priority: "medium" },
      { id: "si-33", label: "Check rich results opportunity", priority: "medium" },
      { id: "si-34", label: "Is AI Overview (SGE) present? How does content respond?", priority: "high" },
      { id: "si-35", label: "Check intent shift over time (old vs new SERP)", priority: "low" },
    ],
  },
  {
    id: "on-page-seo",
    title: "On-Page SEO",
    icon: "📄",
    checks: [
      { id: "op-01", label: "Title tag — includes primary keyword", priority: "high" },
      { id: "op-02", label: "Title tag — within 50-60 characters", priority: "high" },
      { id: "op-03", label: "Title tag — compelling (for CTR)", priority: "high" },
      { id: "op-04", label: "Title tag — includes brand name (if needed)", priority: "medium" },
      { id: "op-05", label: "Title tag — not duplicated anywhere on site", priority: "high" },
      { id: "op-06", label: "Meta description — includes primary keyword", priority: "high" },
      { id: "op-07", label: "Meta description — within 150-160 characters", priority: "high" },
      { id: "op-08", label: "Meta description — includes CTA", priority: "medium" },
      { id: "op-09", label: "Meta description — compelling and unique", priority: "high" },
      { id: "op-10", label: "H1 tag — only one on the page", priority: "high" },
      { id: "op-11", label: "H1 tag — includes primary keyword", priority: "high" },
      { id: "op-12", label: "H1 tag — slightly different from title (variation)", priority: "medium" },
      { id: "op-13", label: "H2 tags — include secondary keywords", priority: "high" },
      { id: "op-14", label: "H2 tags — follow logical structure", priority: "high" },
      { id: "op-15", label: "H3 tags — clearly define sub-points", priority: "medium" },
      { id: "op-16", label: "Heading hierarchy is correct (H1>H2>H3)", priority: "high" },
      { id: "op-17", label: "URL — includes primary keyword", priority: "high" },
      { id: "op-18", label: "URL — short and clean", priority: "high" },
      { id: "op-19", label: "URL — lowercase, hyphens used", priority: "high" },
      { id: "op-20", label: "URL — stop words removed", priority: "medium" },
      { id: "op-21", label: "Keyword density — 1-2% (no stuffing)", priority: "high" },
      { id: "op-22", label: "Primary keyword in first 100 words", priority: "high" },
      { id: "op-23", label: "Primary keyword in last paragraph", priority: "medium" },
      { id: "op-24", label: "LSI keywords used naturally", priority: "high" },
      { id: "op-25", label: "Important terms bolded/italicized", priority: "low" },
      { id: "op-26", label: "Paragraph length — max 3-4 lines (readability)", priority: "medium" },
      { id: "op-27", label: "Sentences short (15-20 words average)", priority: "medium" },
      { id: "op-28", label: "Transition words used", priority: "medium" },
      { id: "op-29", label: "Intro — has hook, keyword, preview of what reader will get", priority: "high" },
      { id: "op-30", label: "Conclusion — has summary, CTA, next step", priority: "high" },
      { id: "op-31", label: "Content is scannable — bullets, numbered lists used", priority: "medium" },
      { id: "op-32", label: "Table of contents present (for long articles)", priority: "medium" },
      { id: "op-33", label: "Anchor text is descriptive (not 'click here')", priority: "high" },
      { id: "op-34", label: "Internal links — minimum 3 relevant links", priority: "high" },
      { id: "op-35", label: "External links — 2-3 authority sources linked", priority: "medium" },
      { id: "op-36", label: "External links — nofollow/sponsored tagged where needed", priority: "medium" },
      { id: "op-37", label: "Images — alt text includes keyword", priority: "high" },
      { id: "op-38", label: "Images — file name is descriptive", priority: "medium" },
      { id: "op-39", label: "Images — compressed (WebP preferred)", priority: "medium" },
      { id: "op-40", label: "Page speed impact — heavy media avoided", priority: "medium" },
      { id: "op-41", label: "Canonical tag is set", priority: "high" },
      { id: "op-42", label: "Meta robots — index, follow set", priority: "high" },
      { id: "op-43", label: "Open Graph tags set (social sharing)", priority: "medium" },
      { id: "op-44", label: "Twitter Card tags set", priority: "low" },
      { id: "op-45", label: "Breadcrumbs present", priority: "medium" },
      { id: "op-46", label: "Mobile-friendly layout", priority: "high" },
      { id: "op-47", label: "Page loading speed optimized (Core Web Vitals)", priority: "high" },
      { id: "op-48", label: "No broken links on page", priority: "high" },
      { id: "op-49", label: "No duplicate content issues", priority: "high" },
      { id: "op-50", label: "Word count is competitive vs competitors", priority: "high" },
      { id: "op-51", label: "Content updated date is visible", priority: "low" },
      { id: "op-52", label: "Author byline present", priority: "medium" },
      { id: "op-53", label: "Social sharing buttons present", priority: "low" },
      { id: "op-54", label: "Comments section appropriate", priority: "low" },
      { id: "op-55", label: "Related posts / content suggestions present", priority: "medium" },
      { id: "op-56", label: "Print-friendly version available", priority: "low" },
      { id: "op-57", label: "Accessibility — proper contrast, font size", priority: "medium" },
      { id: "op-58", label: "No keyword stuffing in headings", priority: "high" },
      { id: "op-59", label: "No hidden text or hidden links", priority: "high" },
      { id: "op-60", label: "Content is original — no plagiarism", priority: "high" },
    ],
  },
  {
    id: "content-writing",
    title: "Content Structure & Writing",
    icon: "✍️",
    checks: [
      { id: "cw-01", label: "Read content brief fully before starting", priority: "high" },
      { id: "cw-02", label: "Clearly understand target audience — who will read this", priority: "high" },
      { id: "cw-03", label: "Decide tone — formal/casual/professional/friendly", priority: "high" },
      { id: "cw-04", label: "Get outline approved before writing", priority: "high" },
      { id: "cw-05", label: "Intro — first sentence grabs attention", priority: "high" },
      { id: "cw-06", label: "Intro — establish problem/question", priority: "high" },
      { id: "cw-07", label: "Intro — give solution/promise", priority: "high" },
      { id: "cw-08", label: "Intro — tell reader what to expect", priority: "medium" },
      { id: "cw-09", label: "Intro — primary keyword in first 100 words", priority: "high" },
      { id: "cw-10", label: "Body — logical flow from section to section", priority: "high" },
      { id: "cw-11", label: "Body — each section covers one idea", priority: "high" },
      { id: "cw-12", label: "Body — transition sentences between sections", priority: "medium" },
      { id: "cw-13", label: "Body — examples / analogies used", priority: "medium" },
      { id: "cw-14", label: "Body — statistics / data cited (with source)", priority: "medium" },
      { id: "cw-15", label: "Body — short paragraphs (max 3-4 lines)", priority: "medium" },
      { id: "cw-16", label: "Body — bullet points where applicable", priority: "medium" },
      { id: "cw-17", label: "Body — numbered lists for steps/processes", priority: "medium" },
      { id: "cw-18", label: "Body — tables for comparisons", priority: "medium" },
      { id: "cw-19", label: "Body — subheadings approximately every 300 words", priority: "medium" },
      { id: "cw-20", label: "Body — no fluff / filler content", priority: "high" },
      { id: "cw-21", label: "Body — active voice used (passive avoided)", priority: "medium" },
      { id: "cw-22", label: "Body — jargon avoided or explained", priority: "medium" },
      { id: "cw-23", label: "Body — no repetition", priority: "medium" },
      { id: "cw-24", label: "Body — facts/claims are accurate", priority: "high" },
      { id: "cw-25", label: "FAQ section — minimum 5 relevant questions answered", priority: "high" },
      { id: "cw-26", label: "FAQ — questions match PAA results", priority: "high" },
      { id: "cw-27", label: "FAQ — concise answers (50-100 words per answer)", priority: "medium" },
      { id: "cw-28", label: "Conclusion — main points summarized", priority: "high" },
      { id: "cw-29", label: "Conclusion — clear CTA", priority: "high" },
      { id: "cw-30", label: "Conclusion — next step / resource suggested", priority: "medium" },
      { id: "cw-31", label: "Word count target achieved", priority: "high" },
      { id: "cw-32", label: "Spelling / grammar checked (Grammarly)", priority: "high" },
      { id: "cw-33", label: "Readability score checked (Flesch 60+ for general audience)", priority: "medium" },
      { id: "cw-34", label: "No AI-sounding generic phrases (leverage, delve, realm)", priority: "high" },
      { id: "cw-35", label: "Human-like writing — personal, specific, real", priority: "high" },
      { id: "cw-36", label: "Brand voice maintained throughout", priority: "medium" },
      { id: "cw-37", label: "Consistent terminology used", priority: "medium" },
      { id: "cw-38", label: "Headings — sentence case or title case consistent", priority: "low" },
      { id: "cw-39", label: "Numbers — consistent format (1 or 'one' — decide one)", priority: "low" },
      { id: "cw-40", label: "Dates — consistent format", priority: "low" },
      { id: "cw-41", label: "Final proofread — fresh eyes", priority: "high" },
      { id: "cw-42", label: "Content value-add check — did reader learn something new?", priority: "high" },
      { id: "cw-43", label: "Content has a unique angle — not a copy", priority: "high" },
      { id: "cw-44", label: "Real-world examples given (not generic)", priority: "medium" },
      { id: "cw-45", label: "Content is scannable — someone skimming still gets value", priority: "medium" },
      { id: "cw-46", label: "Image placement is logical (breaks up text)", priority: "medium" },
      { id: "cw-47", label: "Callout boxes / highlights used (key takeaways)", priority: "low" },
      { id: "cw-48", label: "Content is evergreen or timely — clearly labeled", priority: "medium" },
      { id: "cw-49", label: "Sources are credible (.gov/.edu/.org preferred)", priority: "medium" },
      { id: "cw-50", label: "All links are working", priority: "high" },
      { id: "cw-51", label: "No thin content — every section is substantial", priority: "high" },
      { id: "cw-52", label: "Promise delivered — intro promise fulfilled by content", priority: "high" },
      { id: "cw-53", label: "Content update plan created (6 months/1 year review)", priority: "low" },
      { id: "cw-54", label: "Formatting consistent — fonts, spacing, colors", priority: "medium" },
      { id: "cw-55", label: "Code blocks (if technical) properly formatted", priority: "low" },
      { id: "cw-56", label: "Quotes properly attributed", priority: "medium" },
      { id: "cw-57", label: "No copyright infringement — images licensed", priority: "high" },
      { id: "cw-58", label: "Content submitted on deadline", priority: "high" },
      { id: "cw-59", label: "Content submitted in required format (Google Docs/Word/CMS)", priority: "high" },
      { id: "cw-60", label: "Final sign-off from SEO manager before publish", priority: "high" },
    ],
  },
  {
    id: "nlp-semantic",
    title: "NLP & Semantic SEO",
    icon: "🧠",
    checks: [
      { id: "nl-01", label: "Establish topic authority — cover all related sub-topics", priority: "high" },
      { id: "nl-02", label: "Include semantic keywords (related terms, not just exact match)", priority: "high" },
      { id: "nl-03", label: "Use LSI (Latent Semantic Indexing) keywords", priority: "high" },
      { id: "nl-04", label: "Run TF-IDF analysis — check important terms", priority: "medium" },
      { id: "nl-05", label: "Include NLP entities — people, places, organizations, concepts", priority: "high" },
      { id: "nl-06", label: "Entity co-occurrence — mention related entities together", priority: "medium" },
      { id: "nl-07", label: "Build topic cluster — pillar + supporting pages", priority: "high" },
      { id: "nl-08", label: "Pillar page clearly defined", priority: "high" },
      { id: "nl-09", label: "Supporting cluster pages linked from pillar", priority: "high" },
      { id: "nl-10", label: "Keyword co-occurrence is natural (not forced)", priority: "high" },
      { id: "nl-11", label: "Use synonyms — not just one keyword repeated", priority: "high" },
      { id: "nl-12", label: "Pronoun references are clear (no ambiguous 'it'/'they')", priority: "medium" },
      { id: "nl-13", label: "Concept depth — not surface level, covered in depth", priority: "high" },
      { id: "nl-14", label: "Related concepts addressed (not just main keyword)", priority: "high" },
      { id: "nl-15", label: "Definitions provided for technical terms", priority: "medium" },
      { id: "nl-16", label: "Context established early in content", priority: "high" },
      { id: "nl-17", label: "Topical map created — what to cover on this topic", priority: "medium" },
      { id: "nl-18", label: "Semantic search intent matched", priority: "high" },
      { id: "nl-19", label: "Natural language used — conversational where appropriate", priority: "medium" },
      { id: "nl-20", label: "Question-answer format used (matches NLP patterns)", priority: "high" },
      { id: "nl-21", label: "Co-citations noted — what terms appear together in SERP", priority: "medium" },
      { id: "nl-22", label: "Entity salience high — main topic clearly dominant", priority: "high" },
      { id: "nl-23", label: "Knowledge graph entities referenced (Wikipedia/Wikidata)", priority: "low" },
      { id: "nl-24", label: "Structured data entities match content", priority: "medium" },
      { id: "nl-25", label: "BERT-friendly writing — complete sentences, clear meaning", priority: "high" },
      { id: "nl-26", label: "Long-form content — comprehensive topic coverage", priority: "high" },
      { id: "nl-27", label: "Sub-topics complete — no important aspect missed", priority: "high" },
      { id: "nl-28", label: "Content gap analysis vs competitors (semantic level)", priority: "high" },
      { id: "nl-29", label: "Entity mentions — brand, product, location clearly identified", priority: "medium" },
      { id: "nl-30", label: "Mentally assess semantic relevance score", priority: "medium" },
      { id: "nl-31", label: "Strong topic sentences in every paragraph", priority: "medium" },
      { id: "nl-32", label: "Thematic consistency — no off-topic tangents", priority: "high" },
      { id: "nl-33", label: "Cross-page semantic linking done", priority: "medium" },
      { id: "nl-34", label: "Check content with NLP tool (Surfer SEO/Clearscope if available)", priority: "low" },
      { id: "nl-35", label: "Use contextual anchor text for internal links", priority: "high" },
      { id: "nl-36", label: "Consider phrase-based indexing", priority: "low" },
      { id: "nl-37", label: "Content silos maintained (related content grouped)", priority: "medium" },
      { id: "nl-38", label: "Semantic markup used (Schema, microdata)", priority: "medium" },
      { id: "nl-39", label: "Related words flow naturally (word embeddings concept)", priority: "medium" },
      { id: "nl-40", label: "Final semantic audit — does content feel complete and authoritative?", priority: "high" },
    ],
  },
  {
    id: "eeat",
    title: "E-E-A-T Signals",
    icon: "🏅",
    checks: [
      { id: "ee-01", label: "Experience — show real firsthand experience in content", priority: "high" },
      { id: "ee-02", label: "Experience — use 'I tested this', 'In my experience'", priority: "high" },
      { id: "ee-03", label: "Experience — share specific details (dates, numbers, results)", priority: "high" },
      { id: "ee-04", label: "Experience — photos/screenshots of actual experience (if possible)", priority: "medium" },
      { id: "ee-05", label: "Experience — include personal case study or example", priority: "medium" },
      { id: "ee-06", label: "Expertise — mention author credentials", priority: "high" },
      { id: "ee-07", label: "Expertise — author bio page exists and is linked", priority: "high" },
      { id: "ee-08", label: "Expertise — mention relevant qualifications/certifications", priority: "medium" },
      { id: "ee-09", label: "Expertise — mention years of experience", priority: "medium" },
      { id: "ee-10", label: "Expertise — include expert quotes (third-party validation)", priority: "medium" },
      { id: "ee-11", label: "Expertise — demonstrate industry-specific knowledge", priority: "high" },
      { id: "ee-12", label: "Expertise — ensure technical accuracy", priority: "high" },
      { id: "ee-13", label: "Authoritativeness — cite reputable sources", priority: "high" },
      { id: "ee-14", label: "Authoritativeness — reference industry publications", priority: "medium" },
      { id: "ee-15", label: "Authoritativeness — cite .gov/.edu sources where applicable", priority: "medium" },
      { id: "ee-16", label: "Authoritativeness — present original research / data", priority: "high" },
      { id: "ee-17", label: "Authoritativeness — mention awards / recognitions", priority: "low" },
      { id: "ee-18", label: "Authoritativeness — link to media mentions / press", priority: "low" },
      { id: "ee-19", label: "Trustworthiness — contact information clearly visible", priority: "high" },
      { id: "ee-20", label: "Trustworthiness — privacy policy linked", priority: "high" },
      { id: "ee-21", label: "Trustworthiness — terms of service linked", priority: "medium" },
      { id: "ee-22", label: "Trustworthiness — site is HTTPS secure", priority: "high" },
      { id: "ee-23", label: "Trustworthiness — reviews / testimonials present", priority: "high" },
      { id: "ee-24", label: "Trustworthiness — no misleading claims", priority: "high" },
      { id: "ee-25", label: "Trustworthiness — no factual errors", priority: "high" },
      { id: "ee-26", label: "Trustworthiness — sources clearly cited", priority: "high" },
      { id: "ee-27", label: "Trustworthiness — last updated date visible", priority: "medium" },
      { id: "ee-28", label: "Trustworthiness — corrections policy present (news/health content)", priority: "low" },
      { id: "ee-29", label: "YMYL content? (health/finance/legal) — extra care required", priority: "high" },
      { id: "ee-30", label: "YMYL — medical claims reviewed by doctor", priority: "high" },
      { id: "ee-31", label: "YMYL — financial advice from licensed professional", priority: "high" },
      { id: "ee-32", label: "YMYL — legal content has disclaimer", priority: "high" },
      { id: "ee-33", label: "About page — company/author clearly introduced", priority: "high" },
      { id: "ee-34", label: "Social proof — case studies / success stories present", priority: "medium" },
      { id: "ee-35", label: "External validation — third-party reviews linked", priority: "medium" },
    ],
  },
  {
    id: "aeo-geo",
    title: "AEO / GEO (AI Search Optimization)",
    icon: "🤖",
    checks: [
      { id: "ag-01", label: "Understand AEO — getting into ChatGPT/Gemini/Perplexity answers", priority: "high" },
      { id: "ag-02", label: "Use direct answer format — answer immediately after the question", priority: "high" },
      { id: "ag-03", label: "Use definition-style writing — 'X is Y' format", priority: "high" },
      { id: "ag-04", label: "Concise answers — 40-60 words per answer (AI snippet friendly)", priority: "high" },
      { id: "ag-05", label: "Use structured Q&A format throughout content", priority: "high" },
      { id: "ag-06", label: "Add FAQ schema markup", priority: "high" },
      { id: "ag-07", label: "Add HowTo schema (for process content)", priority: "medium" },
      { id: "ag-08", label: "Use fact-based statements — verifiable claims", priority: "high" },
      { id: "ag-09", label: "Clearly mention brand name — AI models track brand entities", priority: "high" },
      { id: "ag-10", label: "Consistent brand mentions across multiple pages", priority: "high" },
      { id: "ag-11", label: "Write Wikipedia-style introductions", priority: "medium" },
      { id: "ag-12", label: "Use authoritative tone — confident statements", priority: "high" },
      { id: "ag-13", label: "Include statistics and data — AI cites data-backed content", priority: "high" },
      { id: "ag-14", label: "Use numbered lists — AI models prefer list format", priority: "high" },
      { id: "ag-15", label: "Write step-by-step guides — AI prefers step format", priority: "high" },
      { id: "ag-16", label: "Include comparison tables", priority: "medium" },
      { id: "ag-17", label: "Clearly list pros and cons", priority: "medium" },
      { id: "ag-18", label: "Add key takeaways / summary box", priority: "high" },
      { id: "ag-19", label: "Content is backed by authoritative sources", priority: "high" },
      { id: "ag-20", label: "Optimize for Google's AI Overview (SGE)", priority: "high" },
      { id: "ag-21", label: "Check Perplexity AI citation (if already ranking)", priority: "medium" },
      { id: "ag-22", label: "Content structured for ChatGPT plugins / web browsing", priority: "medium" },
      { id: "ag-23", label: "Optimize for Bing AI (Bing Webmaster Tools)", priority: "medium" },
      { id: "ag-24", label: "Voice search optimization — handle conversational queries", priority: "high" },
      { id: "ag-25", label: "Match featured snippet format", priority: "high" },
      { id: "ag-26", label: "Add Speakable schema (voice search)", priority: "low" },
      { id: "ag-27", label: "Maintain content freshness — AI prefers recent content", priority: "high" },
      { id: "ag-28", label: "Entity-based optimization — establish brand as entity", priority: "high" },
      { id: "ag-29", label: "Claim Google Business Profile (Knowledge Panel)", priority: "medium" },
      { id: "ag-30", label: "Create Wikidata entity for brand", priority: "low" },
      { id: "ag-31", label: "Maintain Crunchbase / LinkedIn profile (entity signals)", priority: "medium" },
      { id: "ag-32", label: "Publish press mentions / PR articles", priority: "medium" },
      { id: "ag-33", label: "Include expert quotes from known people", priority: "medium" },
      { id: "ag-34", label: "Build co-citation opportunities", priority: "medium" },
      { id: "ag-35", label: "Monitor unstructured brand mentions", priority: "low" },
      { id: "ag-36", label: "Answer direct questions — '5 best X', 'How to X', 'What is X'", priority: "high" },
      { id: "ag-37", label: "Use 'According to [Brand]' format in content", priority: "medium" },
      { id: "ag-38", label: "Long-form comprehensive content — AI prefers comprehensive sources", priority: "high" },
      { id: "ag-39", label: "No paywalled content if AI citation is the goal", priority: "medium" },
      { id: "ag-40", label: "GEO tracking — monitor if brand is mentioned in AI tools", priority: "high" },
    ],
  },
  {
    id: "local-seo",
    title: "Local SEO Content",
    icon: "📍",
    checks: [
      { id: "ls-01", label: "City + service keyword in H1", priority: "high" },
      { id: "ls-02", label: "NAP (Name, Address, Phone) clearly visible on page", priority: "high" },
      { id: "ls-03", label: "NAP consistent across all pages and directories", priority: "high" },
      { id: "ls-04", label: "Use local phone number", priority: "high" },
      { id: "ls-05", label: "Link to Google Business Profile", priority: "high" },
      { id: "ls-06", label: "Service areas clearly listed", priority: "high" },
      { id: "ls-07", label: "Nearby cities / areas mentioned", priority: "high" },
      { id: "ls-08", label: "Local landmarks mentioned (improves local relevance)", priority: "medium" },
      { id: "ls-09", label: "Local events / news referenced (freshness signal)", priority: "low" },
      { id: "ls-10", label: "Local reviews / testimonials included (with city name)", priority: "high" },
      { id: "ls-11", label: "LocalBusiness schema added", priority: "high" },
      { id: "ls-12", label: "GeoCoordinates schema added", priority: "medium" },
      { id: "ls-13", label: "OpeningHours schema added", priority: "high" },
      { id: "ls-14", label: "ServiceArea schema added", priority: "medium" },
      { id: "ls-15", label: "Google Maps embedded on page", priority: "medium" },
      { id: "ls-16", label: "Directions / how to find us section added", priority: "medium" },
      { id: "ls-17", label: "Local keywords in meta title and description", priority: "high" },
      { id: "ls-18", label: "City name in URL (e.g. /plumber-dubai)", priority: "high" },
      { id: "ls-19", label: "Local case studies / projects mentioned", priority: "high" },
      { id: "ls-20", label: "Community involvement / local partnerships mentioned", priority: "low" },
      { id: "ls-21", label: "Local FAQ — city-specific questions answered", priority: "high" },
      { id: "ls-22", label: "Pricing in local currency", priority: "medium" },
      { id: "ls-23", label: "Local competition acknowledged (builds trust)", priority: "low" },
      { id: "ls-24", label: "Local certifications / licenses mentioned", priority: "medium" },
      { id: "ls-25", label: "Citations built from local authority sites", priority: "medium" },
      { id: "ls-26", label: "City-specific landing page — separate page per major city", priority: "high" },
      { id: "ls-27", label: "Local link building — local newspapers, blogs, directories", priority: "medium" },
      { id: "ls-28", label: "GBP posts regularly updated", priority: "medium" },
      { id: "ls-29", label: "GBP Q&A section optimized", priority: "medium" },
      { id: "ls-30", label: "Review response strategy in place", priority: "medium" },
      { id: "ls-31", label: "Listed on Yelp / TripAdvisor / local directories", priority: "medium" },
      { id: "ls-32", label: "Local pack tracking — keyword + city rankings tracked", priority: "high" },
      { id: "ls-33", label: "'Near me' keywords optimized", priority: "high" },
      { id: "ls-34", label: "Mobile experience excellent (local users mostly on mobile)", priority: "high" },
      { id: "ls-35", label: "Click-to-call button prominent", priority: "high" },
      { id: "ls-36", label: "WhatsApp link added (important in local markets)", priority: "high" },
      { id: "ls-37", label: "Operating hours clearly visible", priority: "high" },
      { id: "ls-38", label: "Local trust signals — years in business, number of clients", priority: "high" },
      { id: "ls-39", label: "Before/after photos included (local service proof)", priority: "medium" },
      { id: "ls-40", label: "Local content hub created — city-specific blog posts", priority: "medium" },
    ],
  },
  {
    id: "schema-markup",
    title: "Schema / Structured Data",
    icon: "🔧",
    checks: [
      { id: "sc-01", label: "Identify correct schema type for page", priority: "high" },
      { id: "sc-02", label: "Article schema — for blog posts", priority: "high" },
      { id: "sc-03", label: "Article schema — headline, author, datePublished, dateModified", priority: "high" },
      { id: "sc-04", label: "FAQ schema — for FAQ sections", priority: "high" },
      { id: "sc-05", label: "HowTo schema — for step-by-step guides", priority: "high" },
      { id: "sc-06", label: "LocalBusiness schema — for local pages", priority: "high" },
      { id: "sc-07", label: "Service schema — for service pages", priority: "high" },
      { id: "sc-08", label: "Product schema — for ecommerce pages", priority: "high" },
      { id: "sc-09", label: "Review/AggregateRating schema — for review pages", priority: "high" },
      { id: "sc-10", label: "BreadcrumbList schema — for breadcrumbs", priority: "medium" },
      { id: "sc-11", label: "Organization schema — for homepage", priority: "high" },
      { id: "sc-12", label: "WebSite schema — for sitelinks searchbox", priority: "medium" },
      { id: "sc-13", label: "Person schema — for author pages", priority: "medium" },
      { id: "sc-14", label: "Event schema — for events", priority: "medium" },
      { id: "sc-15", label: "Video schema — for video content", priority: "medium" },
      { id: "sc-16", label: "ImageObject schema — for important images", priority: "low" },
      { id: "sc-17", label: "SpeakableSpecification schema — for voice search", priority: "low" },
      { id: "sc-18", label: "JSON-LD format used (Google recommended)", priority: "high" },
      { id: "sc-19", label: "Schema validated with Google Rich Results Test", priority: "high" },
      { id: "sc-20", label: "Schema validated with Schema.org Validator", priority: "high" },
      { id: "sc-21", label: "No schema spam — only what is on the page", priority: "high" },
      { id: "sc-22", label: "All required fields filled", priority: "high" },
      { id: "sc-23", label: "Recommended fields also filled", priority: "medium" },
      { id: "sc-24", label: "Nested schema properly structured", priority: "medium" },
      { id: "sc-25", label: "Schema matches page content", priority: "high" },
      { id: "sc-26", label: "Multiple schemas on same page — no conflict", priority: "medium" },
      { id: "sc-27", label: "Schema checked on live page (not just test)", priority: "high" },
      { id: "sc-28", label: "Rich results monitored in Google Search Console", priority: "high" },
      { id: "sc-29", label: "Schema regularly updated (prices, hours change)", priority: "medium" },
      { id: "sc-30", label: "Competitor schema reviewed — what are they using?", priority: "low" },
    ],
  },
  {
    id: "internal-linking",
    title: "Internal Linking Strategy",
    icon: "🔗",
    checks: [
      { id: "il-01", label: "Plan internal link strategy for the page", priority: "high" },
      { id: "il-02", label: "Link from pillar page to cluster pages", priority: "high" },
      { id: "il-03", label: "Link from cluster pages back to pillar page", priority: "high" },
      { id: "il-04", label: "Minimum 3 internal links per page", priority: "high" },
      { id: "il-05", label: "Anchor text is descriptive — keyword-rich", priority: "high" },
      { id: "il-06", label: "Anchor text is natural — not over-optimized", priority: "high" },
      { id: "il-07", label: "No 'click here' or 'read more' anchor text", priority: "high" },
      { id: "il-08", label: "Links point to relevant pages", priority: "high" },
      { id: "il-09", label: "High-value pages given more internal links", priority: "medium" },
      { id: "il-10", label: "No orphan pages — every page has at least one link", priority: "high" },
      { id: "il-11", label: "Link juice flow optimized", priority: "medium" },
      { id: "il-12", label: "Deep links included — not just homepage links", priority: "medium" },
      { id: "il-13", label: "Excessive reciprocal linking avoided", priority: "medium" },
      { id: "il-14", label: "No broken internal links", priority: "high" },
      { id: "il-15", label: "Redirect chains avoided", priority: "medium" },
      { id: "il-16", label: "New content linked from older relevant content", priority: "high" },
      { id: "il-17", label: "Older content updated with links to new pages", priority: "high" },
      { id: "il-18", label: "Navigation links — important pages accessible", priority: "high" },
      { id: "il-19", label: "Footer links — important pages listed", priority: "medium" },
      { id: "il-20", label: "Sidebar links — related content suggested", priority: "medium" },
      { id: "il-21", label: "Related posts section implemented", priority: "medium" },
      { id: "il-22", label: "Link depth checked — important pages within 3 clicks", priority: "medium" },
      { id: "il-23", label: "XML sitemap updated after publishing", priority: "high" },
      { id: "il-24", label: "Internal link audit done quarterly", priority: "low" },
      { id: "il-25", label: "Internal links report checked in Search Console", priority: "medium" },
    ],
  },
  {
    id: "images-media",
    title: "Images & Media SEO",
    icon: "🖼️",
    checks: [
      { id: "im-01", label: "Use relevant images — avoid generic stock photos", priority: "high" },
      { id: "im-02", label: "Use original images / screenshots where possible", priority: "high" },
      { id: "im-03", label: "Image file name is descriptive (keyword-image.jpg not IMG001.jpg)", priority: "high" },
      { id: "im-04", label: "Alt text present on every image", priority: "high" },
      { id: "im-05", label: "Alt text is descriptive and includes keyword naturally", priority: "high" },
      { id: "im-06", label: "Alt text under 125 characters", priority: "medium" },
      { id: "im-07", label: "Decorative images — empty alt text (alt='')", priority: "medium" },
      { id: "im-08", label: "Image file size optimized — preferably under 100KB", priority: "high" },
      { id: "im-09", label: "WebP format used", priority: "high" },
      { id: "im-10", label: "Lazy loading implemented", priority: "medium" },
      { id: "im-11", label: "Image dimensions set (width/height attributes)", priority: "medium" },
      { id: "im-12", label: "Responsive images — srcset used", priority: "medium" },
      { id: "im-13", label: "Image CDN used (if possible)", priority: "low" },
      { id: "im-14", label: "Image sitemap includes important images", priority: "low" },
      { id: "im-15", label: "Large images (1200px) used for Google Discover", priority: "low" },
      { id: "im-16", label: "Original infographics created — shareable", priority: "medium" },
      { id: "im-17", label: "Charts / graphs created from data", priority: "medium" },
      { id: "im-18", label: "Screenshots annotated (arrows, highlights)", priority: "medium" },
      { id: "im-19", label: "Video embedded where available (YouTube preferred)", priority: "medium" },
      { id: "im-20", label: "Video transcript included", priority: "medium" },
      { id: "im-21", label: "Image copyright clear — licensed/original", priority: "high" },
      { id: "im-22", label: "Above-the-fold image is relevant", priority: "medium" },
      { id: "im-23", label: "Image placement fits text flow", priority: "medium" },
      { id: "im-24", label: "Captions added to important images", priority: "low" },
      { id: "im-25", label: "Image search ranking opportunity checked", priority: "low" },
    ],
  },
  {
    id: "page-types",
    title: "Content by Page Type",
    icon: "📋",
    checks: [
      { id: "pt-01", label: "[BLOG] Match target keyword search intent", priority: "high" },
      { id: "pt-02", label: "[BLOG] Compelling headline — number/power word/question", priority: "high" },
      { id: "pt-03", label: "[BLOG] Strong hook intro — story/stat/question", priority: "high" },
      { id: "pt-04", label: "[BLOG] Table of contents included", priority: "medium" },
      { id: "pt-05", label: "[BLOG] Expert quotes included", priority: "medium" },
      { id: "pt-06", label: "[BLOG] Original research / data included", priority: "high" },
      { id: "pt-07", label: "[BLOG] Internal links to related blog posts", priority: "high" },
      { id: "pt-08", label: "[BLOG] Email capture / lead magnet CTA", priority: "medium" },
      { id: "pt-09", label: "[BLOG] Social sharing encouraged", priority: "low" },
      { id: "pt-10", label: "[BLOG] Related posts section present", priority: "medium" },
      { id: "pt-11", label: "[SERVICE PAGE] Primary service keyword in H1", priority: "high" },
      { id: "pt-12", label: "[SERVICE PAGE] Service clearly described (what, how, why)", priority: "high" },
      { id: "pt-13", label: "[SERVICE PAGE] Benefits listed (not just features)", priority: "high" },
      { id: "pt-14", label: "[SERVICE PAGE] Process / how it works explained", priority: "high" },
      { id: "pt-15", label: "[SERVICE PAGE] Pricing or pricing range mentioned", priority: "high" },
      { id: "pt-16", label: "[SERVICE PAGE] Social proof — testimonials, case studies", priority: "high" },
      { id: "pt-17", label: "[SERVICE PAGE] Strong CTA — contact/quote/book now", priority: "high" },
      { id: "pt-18", label: "[SERVICE PAGE] Related services linked", priority: "medium" },
      { id: "pt-19", label: "[SERVICE PAGE] Service schema markup added", priority: "high" },
      { id: "pt-20", label: "[SERVICE PAGE] Trust signals — certifications, years in business", priority: "high" },
      { id: "pt-21", label: "[LOCAL PAGE] City + service keyword in H1 and URL", priority: "high" },
      { id: "pt-22", label: "[LOCAL PAGE] Local phone number prominently visible", priority: "high" },
      { id: "pt-23", label: "[LOCAL PAGE] Physical address mentioned", priority: "high" },
      { id: "pt-24", label: "[LOCAL PAGE] Google Maps embedded", priority: "medium" },
      { id: "pt-25", label: "[LOCAL PAGE] Service area list present", priority: "high" },
      { id: "pt-26", label: "[LOCAL PAGE] Local reviews / testimonials present", priority: "high" },
      { id: "pt-27", label: "[LOCAL PAGE] Local FAQ section present", priority: "high" },
      { id: "pt-28", label: "[LOCAL PAGE] LocalBusiness + Service schema added", priority: "high" },
      { id: "pt-29", label: "[LOCAL PAGE] WhatsApp / local contact method present", priority: "high" },
      { id: "pt-30", label: "[LOCAL PAGE] Mobile-first design", priority: "high" },
      { id: "pt-31", label: "[HOMEPAGE] Brand identity clearly established", priority: "high" },
      { id: "pt-32", label: "[HOMEPAGE] Primary keyword naturally in H1", priority: "high" },
      { id: "pt-33", label: "[HOMEPAGE] Value proposition above fold is clear", priority: "high" },
      { id: "pt-34", label: "[HOMEPAGE] Key services/products section present", priority: "high" },
      { id: "pt-35", label: "[HOMEPAGE] Social proof — numbers, logos, testimonials", priority: "high" },
      { id: "pt-36", label: "[HOMEPAGE] Clear navigation to important pages", priority: "high" },
      { id: "pt-37", label: "[HOMEPAGE] Primary CTA prominent", priority: "high" },
      { id: "pt-38", label: "[HOMEPAGE] Organization schema added", priority: "high" },
      { id: "pt-39", label: "[HOMEPAGE] Page speed is excellent", priority: "high" },
      { id: "pt-40", label: "[HOMEPAGE] Internal links to key pages", priority: "high" },
      { id: "pt-41", label: "[ECOMM] Product title — keyword + key feature", priority: "high" },
      { id: "pt-42", label: "[ECOMM] Product description is unique (not manufacturer copy)", priority: "high" },
      { id: "pt-43", label: "[ECOMM] Key features bullet list present", priority: "high" },
      { id: "pt-44", label: "[ECOMM] Price, availability clearly shown", priority: "high" },
      { id: "pt-45", label: "[ECOMM] Product images from multiple angles", priority: "high" },
      { id: "pt-46", label: "[ECOMM] Reviews enabled", priority: "high" },
      { id: "pt-47", label: "[ECOMM] Product schema markup added", priority: "high" },
      { id: "pt-48", label: "[ECOMM] Related products linked", priority: "medium" },
      { id: "pt-49", label: "[ECOMM] Breadcrumbs present", priority: "medium" },
      { id: "pt-50", label: "[ECOMM] Return policy / shipping info visible", priority: "medium" },
    ],
  },
  {
    id: "post-publish",
    title: "Post-Publish Optimization",
    icon: "🚀",
    checks: [
      { id: "pp-01", label: "Submit URL to Google Search Console (URL Inspection)", priority: "high" },
      { id: "pp-02", label: "Update and resubmit sitemap", priority: "high" },
      { id: "pp-03", label: "Share content on social media", priority: "medium" },
      { id: "pp-04", label: "Link to new page from internal pages", priority: "high" },
      { id: "pp-05", label: "Add link to new page from older related pages", priority: "high" },
      { id: "pp-06", label: "Set up ranking tracking for target keywords", priority: "high" },
      { id: "pp-07", label: "Monitor Google Analytics traffic", priority: "high" },
      { id: "pp-08", label: "Monitor Google Search Console impressions/clicks", priority: "high" },
      { id: "pp-09", label: "Check Core Web Vitals on live page", priority: "high" },
      { id: "pp-10", label: "Run mobile usability test", priority: "high" },
      { id: "pp-11", label: "Run Rich Results Test (live schema validation)", priority: "high" },
      { id: "pp-12", label: "Run PageSpeed Insights", priority: "medium" },
      { id: "pp-13", label: "Plan backlink outreach", priority: "medium" },
      { id: "pp-14", label: "HARO / journalist outreach (if applicable)", priority: "low" },
      { id: "pp-15", label: "Share in email newsletter", priority: "low" },
      { id: "pp-16", label: "Share in relevant communities (Reddit, forums)", priority: "low" },
      { id: "pp-17", label: "Repurpose content — social posts, infographic, video", priority: "low" },
      { id: "pp-18", label: "Check ranking progress at 30 days", priority: "high" },
      { id: "pp-19", label: "Full ranking analysis at 90 days", priority: "high" },
      { id: "pp-20", label: "Set content update schedule (6 months / 1 year)", priority: "medium" },
      { id: "pp-21", label: "Check for broken links on page", priority: "medium" },
      { id: "pp-22", label: "Monitor user engagement metrics (bounce rate, time on page)", priority: "high" },
      { id: "pp-23", label: "Check user behavior with heatmap tool (Hotjar/Clarity)", priority: "low" },
      { id: "pp-24", label: "A/B test title/meta description for CTR", priority: "low" },
      { id: "pp-25", label: "Monitor competitor ranking changes", priority: "medium" },
      { id: "pp-26", label: "Check featured snippet capture", priority: "high" },
      { id: "pp-27", label: "Check PAA presence", priority: "medium" },
      { id: "pp-28", label: "Check local pack presence (if local page)", priority: "medium" },
      { id: "pp-29", label: "Check mention in AI Overview", priority: "medium" },
      { id: "pp-30", label: "Refresh content at 6 months", priority: "medium" },
      { id: "pp-31", label: "Update outdated statistics", priority: "high" },
      { id: "pp-32", label: "Add new PAA questions", priority: "medium" },
      { id: "pp-33", label: "Optimize content for newly ranking keywords", priority: "high" },
      { id: "pp-34", label: "Fix GSC Coverage errors", priority: "high" },
      { id: "pp-35", label: "Check manual actions in GSC", priority: "high" },
      { id: "pp-36", label: "Monitor core update impact", priority: "high" },
      { id: "pp-37", label: "Track earned backlinks", priority: "medium" },
      { id: "pp-38", label: "Monitor referring domains", priority: "medium" },
      { id: "pp-39", label: "Continue link building for this page", priority: "medium" },
      { id: "pp-40", label: "Annual full content audit — keep/improve/delete decision", priority: "high" },
    ],
  },
];

export const getTotalChecks = () =>
  seoSopData.reduce((total, cat) => total + cat.checks.length, 0);

export const getCategoryProgress = (
  categoryId: string,
  checked: Record<string, boolean>
) => {
  const cat = seoSopData.find((c) => c.id === categoryId);
  if (!cat) return { done: 0, total: 0 };
  const done = cat.checks.filter((ch) => checked[ch.id]).length;
  return { done, total: cat.checks.length };
};

export const getOverallProgress = (checked: Record<string, boolean>) => {
  const total = getTotalChecks();
  const done = Object.values(checked).filter(Boolean).length;
  return { done, total };
};
