export interface WriterCheck {
  id: string;
  label: string;
  detail?: string;
  priority: "must" | "should" | "nice";
}

export interface WriterCategory {
  id: string;
  title: string;
  icon: string;
  description: string;
  checks: WriterCheck[];
}

export const writerSopData: WriterCategory[] = [
  {
    id: "brief-reading",
    title: "Brief Reading & Understanding",
    icon: "📋",
    description: "Understand the brief 100% before you start writing",
    checks: [
      { id: "br-01", label: "Read the full brief carefully — do not skip anything", priority: "must" },
      { id: "br-02", label: "Note the primary keyword and remember it", priority: "must" },
      { id: "br-03", label: "Write the secondary keywords list separately", priority: "must" },
      { id: "br-04", label: "Note the target word count", priority: "must" },
      { id: "br-05", label: "Identify the page type — blog/service/local/homepage", priority: "must" },
      { id: "br-06", label: "Clearly understand the target audience — who will read this", priority: "must" },
      { id: "br-07", label: "Note the tone instruction — formal/casual/professional/friendly", priority: "must" },
      { id: "br-08", label: "Note competitor URLs provided in the brief", priority: "must" },
      { id: "br-09", label: "Note special instructions / do's and don'ts", priority: "must" },
      { id: "br-10", label: "Confirm the deadline", priority: "must" },
      { id: "br-11", label: "Confirm submission format — Google Docs/Word/CMS", priority: "must" },
      { id: "br-12", label: "If anything is unclear, ask the SEO manager BEFORE starting", priority: "must" },
      { id: "br-13", label: "NLP terms / semantic entities in brief? Note them", priority: "should" },
      { id: "br-14", label: "Note internal links to add", priority: "should" },
      { id: "br-15", label: "Outline already provided? Follow it or get it approved first", priority: "must" },
    ],
  },
  {
    id: "topic-research",
    title: "Topic & Keyword Research (Writer Level)",
    icon: "🔍",
    description: "Understand the topic deeply — do not write at surface level",
    checks: [
      { id: "tr-01", label: "Search the primary keyword on Google — review the SERP", priority: "must" },
      { id: "tr-02", label: "Open top 3 ranking pages and skim them", priority: "must" },
      { id: "tr-03", label: "Note the headings (H1, H2) of top pages", priority: "must" },
      { id: "tr-04", label: "Roughly note the word count of top pages", priority: "must" },
      { id: "tr-05", label: "List what each competitor covered", priority: "must" },
      { id: "tr-06", label: "Identify content gap — what competitors missed", priority: "must" },
      { id: "tr-07", label: "Note all People Also Ask (PAA) questions", priority: "must" },
      { id: "tr-08", label: "Note related searches (bottom of Google)", priority: "should" },
      { id: "tr-09", label: "Note Google Autocomplete suggestions", priority: "should" },
      { id: "tr-10", label: "Properly read 2-3 authoritative pages on the topic", priority: "must" },
      { id: "tr-11", label: "Any recent news/updates on the topic? Note them", priority: "should" },
      { id: "tr-12", label: "Find statistics and data — from credible sources", priority: "must" },
      { id: "tr-13", label: "Find expert quotes — from industry authorities", priority: "should" },
      { id: "tr-14", label: "Search topic on Reddit/Quora — see real user questions", priority: "should" },
      { id: "tr-15", label: "Search topic on YouTube — note popular video angles", priority: "nice" },
      { id: "tr-16", label: "Wikipedia page available? Read it for background understanding", priority: "should" },
      { id: "tr-17", label: "List related sub-topics for this topic", priority: "must" },
      { id: "tr-18", label: "Note topic-related myths / misconceptions", priority: "nice" },
      { id: "tr-19", label: "Note topic background / history if relevant", priority: "nice" },
      { id: "tr-20", label: "After research — can you write confidently? If not, research more", priority: "must" },
    ],
  },
  {
    id: "outline-creation",
    title: "Outline Creation",
    icon: "🗂️",
    description: "Create outline first, then write — never write directly without an outline",
    checks: [
      { id: "oc-01", label: "Write the outline before content — mandatory", priority: "must" },
      { id: "oc-02", label: "Draft H1 (title) — keyword + power word + benefit", priority: "must" },
      { id: "oc-03", label: "Plan intro section — hook, problem, promise, preview", priority: "must" },
      { id: "oc-04", label: "List main H2 sections — in logical order", priority: "must" },
      { id: "oc-05", label: "Note H3 sub-points under each H2", priority: "must" },
      { id: "oc-06", label: "Include FAQ section — plan minimum 5 questions", priority: "must" },
      { id: "oc-07", label: "Plan conclusion section", priority: "must" },
      { id: "oc-08", label: "Does outline cover competitor gaps?", priority: "must" },
      { id: "oc-09", label: "Does outline address PAA questions?", priority: "must" },
      { id: "oc-10", label: "Does the outline follow logical flow? Check sequence", priority: "must" },
      { id: "oc-11", label: "Rough word count split — how many words per section", priority: "should" },
      { id: "oc-12", label: "No duplicate sections in outline?", priority: "must" },
      { id: "oc-13", label: "Does outline fulfill the title's promise?", priority: "must" },
      { id: "oc-14", label: "Get outline approved by SEO manager (if required)", priority: "should" },
      { id: "oc-15", label: "Only start writing after outline is approved", priority: "must" },
    ],
  },
  {
    id: "title-writing",
    title: "Title (H1) Writing",
    icon: "🏷️",
    description: "The title is the first impression — make it perfect",
    checks: [
      { id: "tw-01", label: "Primary keyword is in the title", priority: "must" },
      { id: "tw-02", label: "Title is within 50-70 characters", priority: "must" },
      { id: "tw-03", label: "Title is compelling — someone would want to click", priority: "must" },
      { id: "tw-04", label: "Use a number in title if applicable (e.g. '10 Best')", priority: "should" },
      { id: "tw-05", label: "Use a power word (Ultimate, Complete, Proven, Expert)", priority: "should" },
      { id: "tw-06", label: "Benefit/outcome is clear in title", priority: "must" },
      { id: "tw-07", label: "Try question format if it matches intent", priority: "nice" },
      { id: "tw-08", label: "Include current year if evergreen content (e.g. 2025)", priority: "should" },
      { id: "tw-09", label: "No clickbait — content delivers what title promises", priority: "must" },
      { id: "tw-10", label: "Meta title is slightly different from H1", priority: "should" },
      { id: "tw-11", label: "Write 2-3 title alternatives and choose the best", priority: "should" },
      { id: "tw-12", label: "Title is better and more unique than competitor titles", priority: "must" },
    ],
  },
  {
    id: "intro-writing",
    title: "Introduction Writing",
    icon: "🚪",
    description: "Hook the reader in the first 3 seconds or they will leave",
    checks: [
      { id: "iw-01", label: "First sentence grabs attention — stat/question/bold claim", priority: "must" },
      { id: "iw-02", label: "Primary keyword appears naturally in first 100 words", priority: "must" },
      { id: "iw-03", label: "Acknowledge the reader's problem / pain point", priority: "must" },
      { id: "iw-04", label: "Give solution/promise — 'In this article you will learn...'", priority: "must" },
      { id: "iw-05", label: "Give a preview — what will be covered in the article", priority: "should" },
      { id: "iw-06", label: "Intro is not more than 100-150 words (for blogs)", priority: "must" },
      { id: "iw-07", label: "No fluff in intro — get to the point", priority: "must" },
      { id: "iw-08", label: "No generic openers — avoid 'In today's world...'", priority: "must" },
      { id: "iw-09", label: "Talk directly to reader — use 'you/your'", priority: "should" },
      { id: "iw-10", label: "After the intro, reader wants to keep reading", priority: "must" },
      { id: "iw-11", label: "Start with a stat if strong data is available", priority: "should" },
      { id: "iw-12", label: "Start with a story/scenario if there is a relatable angle", priority: "nice" },
      { id: "iw-13", label: "No keyword stuffing in intro", priority: "must" },
      { id: "iw-14", label: "Tone is established from the intro", priority: "must" },
    ],
  },
  {
    id: "body-writing",
    title: "Body Content Writing",
    icon: "✍️",
    description: "Main content — this is where writing skills show",
    checks: [
      { id: "bw-01", label: "Each H2 section covers one main idea — do not mix", priority: "must" },
      { id: "bw-02", label: "Secondary keywords used naturally in H2 headings", priority: "must" },
      { id: "bw-03", label: "H3 subheadings break down each H2 further", priority: "must" },
      { id: "bw-04", label: "Short paragraphs — max 3-4 lines", priority: "must" },
      { id: "bw-05", label: "Each paragraph starts with a topic sentence", priority: "must" },
      { id: "bw-06", label: "Transition sentences written between sections", priority: "must" },
      { id: "bw-07", label: "Active voice used — passive voice avoided", priority: "must" },
      { id: "bw-08", label: "Simple language — jargon explained or avoided", priority: "must" },
      { id: "bw-09", label: "Short sentences — 15-20 words average", priority: "must" },
      { id: "bw-10", label: "Bullet points used for list items", priority: "must" },
      { id: "bw-11", label: "Numbered lists used for steps/processes", priority: "must" },
      { id: "bw-12", label: "Tables used for comparisons", priority: "should" },
      { id: "bw-13", label: "Real-world examples included — specific, not generic", priority: "must" },
      { id: "bw-14", label: "Statistics cited with source", priority: "must" },
      { id: "bw-15", label: "Expert quotes included", priority: "should" },
      { id: "bw-16", label: "Analogies used to explain complex concepts", priority: "should" },
      { id: "bw-17", label: "No repetition — same point not made multiple times", priority: "must" },
      { id: "bw-18", label: "No fluff — every sentence adds value", priority: "must" },
      { id: "bw-19", label: "Logical flow maintained — A leads to B leads to C", priority: "must" },
      { id: "bw-20", label: "Practical advice given in every section — not just theory", priority: "must" },
      { id: "bw-21", label: "Important terms / key takeaways bolded", priority: "should" },
      { id: "bw-22", label: "Callout boxes added for key points", priority: "nice" },
      { id: "bw-23", label: "Code blocks used properly if technical content", priority: "must" },
      { id: "bw-24", label: "Every claim backed by evidence, example or logic", priority: "must" },
      { id: "bw-25", label: "Depth maintained — do not stay at surface level", priority: "must" },
      { id: "bw-26", label: "Each H2 section is substantial — minimum 150-200 words", priority: "must" },
      { id: "bw-27", label: "Content is skimmable — headings/bullets provide value even when skimming", priority: "must" },
      { id: "bw-28", label: "Brand voice consistent throughout", priority: "must" },
      { id: "bw-29", label: "Word count tracked — maintain pace", priority: "should" },
      { id: "bw-30", label: "Facts double-checked before writing", priority: "must" },
    ],
  },
  {
    id: "keyword-usage",
    title: "Keyword Usage in Content",
    icon: "🔑",
    description: "Use keywords naturally — write for humans, not robots",
    checks: [
      { id: "ku-01", label: "Primary keyword is in H1", priority: "must" },
      { id: "ku-02", label: "Primary keyword is in first 100 words", priority: "must" },
      { id: "ku-03", label: "Primary keyword appears naturally in 2-3 H2 headings", priority: "must" },
      { id: "ku-04", label: "Primary keyword is in the last paragraph", priority: "should" },
      { id: "ku-05", label: "Primary keyword density is 1-2% — check it", priority: "must" },
      { id: "ku-06", label: "Absolutely no keyword stuffing — natural flow", priority: "must" },
      { id: "ku-07", label: "Secondary keywords appear naturally in body", priority: "must" },
      { id: "ku-08", label: "Synonyms used — same keyword not repeated constantly", priority: "must" },
      { id: "ku-09", label: "LSI keywords (related terms) used naturally", priority: "must" },
      { id: "ku-10", label: "NLP terms from brief included in content", priority: "must" },
      { id: "ku-11", label: "Semantic entities mentioned — relevant people/places/brands", priority: "should" },
      { id: "ku-12", label: "Keyword in image alt text", priority: "must" },
      { id: "ku-13", label: "Keywords used in anchor text for internal links", priority: "should" },
      { id: "ku-14", label: "Keywords do not feel forced — they flow naturally", priority: "must" },
      { id: "ku-15", label: "PAA question wording used naturally when answering FAQs", priority: "must" },
    ],
  },
  {
    id: "faq-writing",
    title: "FAQ Section Writing",
    icon: "❓",
    description: "FAQs are not just formality — they are gold for featured snippets and AI search",
    checks: [
      { id: "fw-01", label: "Minimum 5 FAQ questions — ideally 7-8", priority: "must" },
      { id: "fw-02", label: "Questions match People Also Ask (PAA) results", priority: "must" },
      { id: "fw-03", label: "Questions written in real user language — natural tone", priority: "must" },
      { id: "fw-04", label: "First sentence is the direct answer — context comes after", priority: "must" },
      { id: "fw-05", label: "Each answer is concise — 40-80 words", priority: "must" },
      { id: "fw-06", label: "Keyword included naturally in the question", priority: "must" },
      { id: "fw-07", label: "Secondary / related keywords used naturally in answers", priority: "should" },
      { id: "fw-08", label: "Include a 'What is X' format question", priority: "must" },
      { id: "fw-09", label: "Include a 'How to X' format question", priority: "must" },
      { id: "fw-10", label: "Include a 'Why X' format question", priority: "should" },
      { id: "fw-11", label: "Include a 'Best X' or 'Top X' question", priority: "should" },
      { id: "fw-12", label: "Beginner-level doubts addressed", priority: "must" },
      { id: "fw-13", label: "1-2 advanced questions included", priority: "nice" },
      { id: "fw-14", label: "FAQ answers are factually accurate", priority: "must" },
      { id: "fw-15", label: "FAQ section placed at end of content, before conclusion", priority: "should" },
    ],
  },
  {
    id: "conclusion-writing",
    title: "Conclusion Writing",
    icon: "🏁",
    description: "Last impression — send the reader to take action",
    checks: [
      { id: "cw-01", label: "Briefly summarize the main points", priority: "must" },
      { id: "cw-02", label: "Primary keyword appears naturally in conclusion", priority: "must" },
      { id: "cw-03", label: "Conclusion should be 100-150 words", priority: "must" },
      { id: "cw-04", label: "Clear CTA — subscribe/share/contact/related article", priority: "must" },
      { id: "cw-05", label: "CTA matches page type — blog: subscribe/share, service: contact, local: call now", priority: "must" },
      { id: "cw-06", label: "Suggest related resource / next article — internal link", priority: "should" },
      { id: "cw-07", label: "Empower the reader — 'Now you are ready to...'", priority: "should" },
      { id: "cw-08", label: "No new information introduced in conclusion", priority: "must" },
      { id: "cw-09", label: "Conclusion is not abrupt — smooth ending", priority: "must" },
      { id: "cw-10", label: "Promise made in intro is confirmed as fulfilled", priority: "must" },
    ],
  },
  {
    id: "content-quality",
    title: "Content Quality & Originality",
    icon: "💎",
    description: "Low quality = no rankings. Do not skip this section",
    checks: [
      { id: "cq-01", label: "Content is 100% original — absolutely no copy-paste", priority: "must" },
      { id: "cq-02", label: "Run plagiarism check — Grammarly/Copyscape/SmallSEOTools", priority: "must" },
      { id: "cq-03", label: "No AI-generic phrases — 'delve', 'leverage', 'realm', 'crucial', 'comprehensive'", priority: "must" },
      { id: "cq-04", label: "Content feels human — personal, specific, real examples", priority: "must" },
      { id: "cq-05", label: "Content provides a unique angle — better than competitors", priority: "must" },
      { id: "cq-06", label: "No thin sections — every part is substantial", priority: "must" },
      { id: "cq-07", label: "Facts are accurate — no wrong information", priority: "must" },
      { id: "cq-08", label: "Sources are credible — Wikipedia, news, .gov, .edu, industry sites", priority: "must" },
      { id: "cq-09", label: "Content achieves target word count", priority: "must" },
      { id: "cq-10", label: "Content fully answers the reader's query", priority: "must" },
      { id: "cq-11", label: "Content has real value — reader learns something actionable", priority: "must" },
      { id: "cq-12", label: "Content is engaging — not boring throughout", priority: "must" },
      { id: "cq-13", label: "Consistent terminology — one term, one meaning", priority: "must" },
      { id: "cq-14", label: "No contradictions — content gives one consistent message", priority: "must" },
      { id: "cq-15", label: "Content matches the audience's level — not too basic or too advanced", priority: "must" },
      { id: "cq-16", label: "Personal experience / opinion added where relevant", priority: "should" },
      { id: "cq-17", label: "Storytelling elements present", priority: "nice" },
      { id: "cq-18", label: "Humor/personality present (if brand allows)", priority: "nice" },
      { id: "cq-19", label: "Content does not contain outdated information", priority: "must" },
      { id: "cq-20", label: "Content feels trustworthy — like a reliable source", priority: "must" },
    ],
  },
  {
    id: "eeat-writer",
    title: "E-E-A-T (Writer Responsibility)",
    icon: "🏅",
    description: "Make Google and the reader trust your content — show it in the writing",
    checks: [
      { id: "et-01", label: "Show experience — 'I have personally tested/used/seen this'", priority: "must" },
      { id: "et-02", label: "Share specific details that prove real experience — dates, numbers, results", priority: "must" },
      { id: "et-03", label: "Demonstrate expertise — show deep knowledge, not generic content", priority: "must" },
      { id: "et-04", label: "Use technical terms correctly — no wrong terminology", priority: "must" },
      { id: "et-05", label: "Show industry-specific knowledge — avoid being generic", priority: "must" },
      { id: "et-06", label: "Include expert quotes — reference known professionals", priority: "should" },
      { id: "et-07", label: "Cite authoritative sources — with links", priority: "must" },
      { id: "et-08", label: "Reference research papers / studies where applicable", priority: "should" },
      { id: "et-09", label: "Provide sources for factual claims", priority: "must" },
      { id: "et-10", label: "No misleading claims — avoid exaggeration", priority: "must" },
      { id: "et-11", label: "YMYL content (health/finance/legal) — extra care, add disclaimer", priority: "must" },
      { id: "et-12", label: "Author credentials clearly mentioned in bio (if applicable)", priority: "should" },
      { id: "et-13", label: "Share a case study / real result if possible", priority: "should" },
      { id: "et-14", label: "Content is balanced — both sides covered where appropriate", priority: "should" },
      { id: "et-15", label: "No sponsored/biased content — honest reviews and recommendations", priority: "must" },
    ],
  },
  {
    id: "aeo-writing",
    title: "AEO / AI Search Optimization Writing",
    icon: "🤖",
    description: "Get into ChatGPT, Gemini, Perplexity — the future is AI search",
    checks: [
      { id: "aw-01", label: "Write definition-style sentences — 'X is Y that does Z'", priority: "must" },
      { id: "aw-02", label: "Give direct answer in first sentence for every main question", priority: "must" },
      { id: "aw-03", label: "Write concise answers — 40-60 words per concept", priority: "must" },
      { id: "aw-04", label: "Use numbered lists — AI models prefer numbered format", priority: "must" },
      { id: "aw-05", label: "Use step-by-step format for processes", priority: "must" },
      { id: "aw-06", label: "Write factual, verifiable statements — clearly label opinions", priority: "must" },
      { id: "aw-07", label: "Clearly and consistently mention brand name throughout", priority: "must" },
      { id: "aw-08", label: "Add key takeaways / summary section — AI loves summaries", priority: "must" },
      { id: "aw-09", label: "Clearly list pros and cons where applicable", priority: "should" },
      { id: "aw-10", label: "Use comparison format (X vs Y) where applicable", priority: "should" },
      { id: "aw-11", label: "Include statistics and data — AI cites data-backed content", priority: "must" },
      { id: "aw-12", label: "Write Wikipedia-style opening paragraph — encyclopedic intro", priority: "should" },
      { id: "aw-13", label: "Use authoritative and confident tone", priority: "must" },
      { id: "aw-14", label: "Use conversational Q&A format in FAQs", priority: "must" },
      { id: "aw-15", label: "Content is comprehensive — AI prefers comprehensive sources", priority: "must" },
      { id: "aw-16", label: "No ambiguous language — clear, specific statements", priority: "must" },
      { id: "aw-17", label: "Use 'According to [Brand/Expert]' format", priority: "nice" },
      { id: "aw-18", label: "Content is up-to-date — stale info confuses AI", priority: "must" },
    ],
  },
  {
    id: "blog-specific",
    title: "Blog Post Writing (Specific)",
    icon: "📝",
    description: "Specific rules for blogs — informational content guidelines",
    checks: [
      { id: "bs-01", label: "Blog title is compelling — number/power word/curiosity/benefit", priority: "must" },
      { id: "bs-02", label: "Strong intro hook — reader is engaged from the first line", priority: "must" },
      { id: "bs-03", label: "Table of contents included (for 1500+ word articles)", priority: "must" },
      { id: "bs-04", label: "Subheadings every 300 words", priority: "must" },
      { id: "bs-05", label: "Blog post has storytelling — not just dry information", priority: "should" },
      { id: "bs-06", label: "Actionable tips included — reader can act on the content", priority: "must" },
      { id: "bs-07", label: "Blog post clearly fulfills 'how to', 'what is', or 'best X' intent", priority: "must" },
      { id: "bs-08", label: "Images / screenshots included (min 2-3)", priority: "should" },
      { id: "bs-09", label: "Alt text written for each image", priority: "must" },
      { id: "bs-10", label: "Internal links — 3-5 related blog posts or service pages linked", priority: "must" },
      { id: "bs-11", label: "External links — 2-3 authority sites linked as sources", priority: "must" },
      { id: "bs-12", label: "Blog word count: informational = 1500-2500, pillar = 3000-5000", priority: "must" },
      { id: "bs-13", label: "Blog contains original data or unique insight", priority: "should" },
      { id: "bs-14", label: "Blog conclusion has newsletter/resource CTA", priority: "should" },
      { id: "bs-15", label: "Meta description written — compelling, 150-160 chars, keyword included", priority: "must" },
      { id: "bs-16", label: "Author byline set", priority: "should" },
      { id: "bs-17", label: "Publish date is accurate", priority: "must" },
      { id: "bs-18", label: "Blog tags / categories set", priority: "should" },
      { id: "bs-19", label: "Featured image is relevant and attractive", priority: "must" },
      { id: "bs-20", label: "Content is social sharing friendly — catchy title + image", priority: "should" },
    ],
  },
  {
    id: "service-page-specific",
    title: "Service Page Writing (Specific)",
    icon: "🛠️",
    description: "Service pages convert visitors — every word matters here",
    checks: [
      { id: "sp-01", label: "H1 clearly contains the primary service keyword", priority: "must" },
      { id: "sp-02", label: "Above the fold — what the service is, who it is for, where — all clear", priority: "must" },
      { id: "sp-03", label: "Service clearly described — exactly what you do", priority: "must" },
      { id: "sp-04", label: "Benefits listed — not features, but what the client gets", priority: "must" },
      { id: "sp-05", label: "Process explained — 'How it works' step by step", priority: "must" },
      { id: "sp-06", label: "Pricing or pricing range mentioned (trust signal)", priority: "should" },
      { id: "sp-07", label: "Social proof — testimonials, case studies, client names", priority: "must" },
      { id: "sp-08", label: "Results / outcomes mentioned — backed with numbers", priority: "must" },
      { id: "sp-09", label: "Strong CTA — 'Get a Free Quote', 'Contact Us Today', 'Book Now'", priority: "must" },
      { id: "sp-10", label: "Multiple CTAs — top, middle, bottom of page", priority: "should" },
      { id: "sp-11", label: "USP (Unique Selling Proposition) clearly stated", priority: "must" },
      { id: "sp-12", label: "Trust signals — certifications, years in business, team size", priority: "must" },
      { id: "sp-13", label: "FAQ section added — handle objections", priority: "must" },
      { id: "sp-14", label: "Related services linked — internal linking", priority: "must" },
      { id: "sp-15", label: "Service page tone is professional and confident", priority: "must" },
      { id: "sp-16", label: "Target audience clearly addressed — 'For businesses who...'", priority: "should" },
      { id: "sp-17", label: "Pain points addressed — reader's problem acknowledged", priority: "must" },
      { id: "sp-18", label: "Service page word count: 800-1500 words", priority: "must" },
      { id: "sp-19", label: "No fluff — every sentence drives toward conversion", priority: "must" },
      { id: "sp-20", label: "Meta description includes CTA", priority: "must" },
    ],
  },
  {
    id: "local-page-specific",
    title: "Local Landing Page Writing (Specific)",
    icon: "📍",
    description: "Local SEO pages — city + service + trust = rankings",
    checks: [
      { id: "lp-01", label: "H1 contains city + service keyword — e.g. 'Plumber in Dubai'", priority: "must" },
      { id: "lp-02", label: "URL contains city name — /plumber-dubai", priority: "must" },
      { id: "lp-03", label: "City name and service prominently mentioned in intro", priority: "must" },
      { id: "lp-04", label: "Physical address clearly mentioned", priority: "must" },
      { id: "lp-05", label: "Local phone number mentioned", priority: "must" },
      { id: "lp-06", label: "Service areas listed — specific neighbourhoods/areas", priority: "must" },
      { id: "lp-07", label: "Local landmarks mentioned — 'Near Dubai Mall', 'Serving Gulshan area'", priority: "should" },
      { id: "lp-08", label: "Local testimonials included — with city name", priority: "must" },
      { id: "lp-09", label: "Local case study or project mentioned", priority: "should" },
      { id: "lp-10", label: "Local FAQ written — city-specific questions", priority: "must" },
      { id: "lp-11", label: "Local trust signals — local awards, years serving city", priority: "should" },
      { id: "lp-12", label: "Community involvement mentioned if applicable", priority: "nice" },
      { id: "lp-13", label: "City-specific pricing or information mentioned", priority: "should" },
      { id: "lp-14", label: "WhatsApp number / preferred local contact method added", priority: "must" },
      { id: "lp-15", label: "Operating hours clearly mentioned", priority: "must" },
      { id: "lp-16", label: "'Near me' variations used naturally — '...near you in [city]'", priority: "should" },
      { id: "lp-17", label: "Local page word count: 600-1000 words is sufficient", priority: "must" },
      { id: "lp-18", label: "Content is unique — not copy-pasted from other city pages", priority: "must" },
      { id: "lp-19", label: "Request SEO manager to embed Google Maps", priority: "should" },
      { id: "lp-20", label: "Strong local CTA — 'Call Now', 'Get Free Quote in [City]'", priority: "must" },
    ],
  },
  {
    id: "homepage-writing",
    title: "Homepage Writing (Specific)",
    icon: "🏠",
    description: "Homepage = brand's first impression + SEO foundation",
    checks: [
      { id: "hw-01", label: "Hero section — what you do, for whom, where — in one sentence", priority: "must" },
      { id: "hw-02", label: "Primary keyword naturally in H1", priority: "must" },
      { id: "hw-03", label: "Value proposition above the fold is clear", priority: "must" },
      { id: "hw-04", label: "Primary CTA above fold visible — 'Get Started', 'Contact Us'", priority: "must" },
      { id: "hw-05", label: "Services/Products overview section present", priority: "must" },
      { id: "hw-06", label: "Each service briefly described and linked to service page", priority: "must" },
      { id: "hw-07", label: "Social proof section — numbers, logos, testimonials", priority: "must" },
      { id: "hw-08", label: "Trust signals — years in business, clients served, awards", priority: "must" },
      { id: "hw-09", label: "Brief About section — brand story in short", priority: "should" },
      { id: "hw-10", label: "Blog / resources section linked", priority: "should" },
      { id: "hw-11", label: "Contact section / footer contact info is clear", priority: "must" },
      { id: "hw-12", label: "Homepage tone matches brand identity", priority: "must" },
      { id: "hw-13", label: "Homepage word count: 500-800 words (concise)", priority: "must" },
      { id: "hw-14", label: "No jargon — anyone visiting should understand", priority: "must" },
      { id: "hw-15", label: "Internal links to key pages — services, about, contact, blog", priority: "must" },
    ],
  },
  {
    id: "ecomm-writing",
    title: "eCommerce Product Page Writing",
    icon: "🛒",
    description: "Product description should convert — lead visitor to the buy button",
    checks: [
      { id: "ep-01", label: "Product title — keyword + key feature + brand (if applicable)", priority: "must" },
      { id: "ep-02", label: "Short description — 50-100 words, key benefits as bullet points", priority: "must" },
      { id: "ep-03", label: "Long description — 200-400 words, features + benefits + use cases", priority: "must" },
      { id: "ep-04", label: "Product description is not manufacturer copy — write uniquely", priority: "must" },
      { id: "ep-05", label: "Features clearly listed — specs, dimensions, materials", priority: "must" },
      { id: "ep-06", label: "Benefits clearly listed — convert features into benefits", priority: "must" },
      { id: "ep-07", label: "Use cases / who it is for — clearly mentioned", priority: "should" },
      { id: "ep-08", label: "Sensory language used — how it looks, feels, works", priority: "should" },
      { id: "ep-09", label: "Social proof — reviews highlighted", priority: "must" },
      { id: "ep-10", label: "Price anchored — value justified", priority: "should" },
      { id: "ep-11", label: "Urgency / scarcity added if applicable — 'Limited Stock'", priority: "nice" },
      { id: "ep-12", label: "Shipping / return policy briefly mentioned", priority: "must" },
      { id: "ep-13", label: "Related products / upsell section noted for SEO manager", priority: "should" },
      { id: "ep-14", label: "Image alt text written descriptively — product + keyword", priority: "must" },
      { id: "ep-15", label: "FAQ section added — common product questions", priority: "should" },
    ],
  },
  {
    id: "gmb-writing",
    title: "Google Business Profile (GMB) Post Writing",
    icon: "📌",
    description: "GMB posts — boost local visibility",
    checks: [
      { id: "gw-01", label: "Identify post type — Offer/Update/Event/Product", priority: "must" },
      { id: "gw-02", label: "Post should be 150-300 words", priority: "must" },
      { id: "gw-03", label: "Include primary keyword / service keyword naturally", priority: "must" },
      { id: "gw-04", label: "Mention city name in post", priority: "must" },
      { id: "gw-05", label: "Clear CTA added — 'Call Now', 'Book', 'Learn More'", priority: "must" },
      { id: "gw-06", label: "Offer posts include expiry date", priority: "must" },
      { id: "gw-07", label: "Post is engaging — value-driven, not just boring facts", priority: "must" },
      { id: "gw-08", label: "Suggest a relevant image for the post", priority: "should" },
      { id: "gw-09", label: "No hashtags in GMB posts", priority: "must" },
      { id: "gw-10", label: "Post is consistent with brand voice", priority: "must" },
    ],
  },
  {
    id: "formatting",
    title: "Formatting & Structure",
    icon: "📐",
    description: "Poorly formatted content = bad UX = bad SEO. Format properly.",
    checks: [
      { id: "fm-01", label: "Only one H1 in the entire document", priority: "must" },
      { id: "fm-02", label: "H2s used for main sections", priority: "must" },
      { id: "fm-03", label: "H3s used for sub-sections within H2s", priority: "must" },
      { id: "fm-04", label: "Heading hierarchy correct — H1 > H2 > H3 (no H3 directly under H1)", priority: "must" },
      { id: "fm-05", label: "Paragraphs max 3-4 lines", priority: "must" },
      { id: "fm-06", label: "Bullet points max 5-7 items per list", priority: "should" },
      { id: "fm-07", label: "Bold used only for important terms — not everything", priority: "must" },
      { id: "fm-08", label: "Italics used for quotes or emphasis", priority: "nice" },
      { id: "fm-09", label: "Tables properly formatted — header row present", priority: "must" },
      { id: "fm-10", label: "Table of contents anchor links work properly", priority: "must" },
      { id: "fm-11", label: "Whitespace used properly — no walls of text", priority: "must" },
      { id: "fm-12", label: "Content sections clearly separated visually", priority: "must" },
      { id: "fm-13", label: "Consistent capitalization — title case or sentence case", priority: "must" },
      { id: "fm-14", label: "Numbers consistent — figures (1,2,3) or words (one, two)", priority: "should" },
      { id: "fm-15", label: "No extra blank lines or random spacing", priority: "must" },
      { id: "fm-16", label: "Code blocks properly formatted (if technical content)", priority: "must" },
      { id: "fm-17", label: "Quotes properly attributed and formatted", priority: "must" },
      { id: "fm-18", label: "Document is clean — no leftover draft notes", priority: "must" },
    ],
  },
  {
    id: "internal-links-writer",
    title: "Internal Linking (Writer Role)",
    icon: "🔗",
    description: "Writer's job — link relevant pages within the content",
    checks: [
      { id: "il-01", label: "Minimum 3 internal links in every article", priority: "must" },
      { id: "il-02", label: "Internal links point to relevant pages", priority: "must" },
      { id: "il-03", label: "Anchor text is descriptive — not 'click here', use 'learn about SEO audits'", priority: "must" },
      { id: "il-04", label: "Keyword naturally included in anchor text", priority: "should" },
      { id: "il-05", label: "Links fit naturally in content — not forced", priority: "must" },
      { id: "il-06", label: "Pillar page linked from cluster pages", priority: "must" },
      { id: "il-07", label: "Related blog posts linked", priority: "should" },
      { id: "il-08", label: "Service pages linked where relevant", priority: "should" },
      { id: "il-09", label: "External links go to authority sites — Wikipedia, research, news", priority: "must" },
      { id: "il-10", label: "External links should open in new tab — inform SEO manager", priority: "should" },
    ],
  },
  {
    id: "images-writer",
    title: "Images & Media (Writer Role)",
    icon: "🖼️",
    description: "Writer is responsible for image placement and alt text",
    checks: [
      { id: "img-01", label: "Identify where images are needed — where visuals help explain content", priority: "must" },
      { id: "img-02", label: "Suggest featured image — relevant to topic", priority: "must" },
      { id: "img-03", label: "Write alt text for every image — descriptive with keyword", priority: "must" },
      { id: "img-04", label: "Alt text under 125 characters", priority: "must" },
      { id: "img-05", label: "Write descriptive image file names — keyword-description.jpg", priority: "must" },
      { id: "img-06", label: "Include screenshots where applicable — especially in how-to guides", priority: "should" },
      { id: "img-07", label: "Suggest infographic if there is complex data", priority: "nice" },
      { id: "img-08", label: "Suggest chart/graph if there are statistics", priority: "nice" },
      { id: "img-09", label: "Image placement is logical — near related text", priority: "must" },
      { id: "img-10", label: "Captions added where helpful", priority: "nice" },
      { id: "img-11", label: "Avoid stock photos — use original/contextual images", priority: "should" },
      { id: "img-12", label: "Images are copyright clear — licensed or original", priority: "must" },
    ],
  },
  {
    id: "proofreading",
    title: "Proofreading & Editing",
    icon: "🔎",
    description: "Do this before submitting — read with fresh eyes once",
    checks: [
      { id: "pr-01", label: "Check spelling errors — run Grammarly", priority: "must" },
      { id: "pr-02", label: "Fix grammar errors", priority: "must" },
      { id: "pr-03", label: "Punctuation is correct", priority: "must" },
      { id: "pr-04", label: "Sentence structure is clear — rewrite ambiguous sentences", priority: "must" },
      { id: "pr-05", label: "Check readability — use Hemingway App", priority: "should" },
      { id: "pr-06", label: "Target Grade 7-8 reading level (for general content)", priority: "should" },
      { id: "pr-07", label: "Check passive voice instances and convert to active", priority: "must" },
      { id: "pr-08", label: "Remove wordiness — 'in order to' → 'to', 'due to the fact that' → 'because'", priority: "must" },
      { id: "pr-09", label: "Remove cliches — 'at the end of the day', 'think outside the box'", priority: "must" },
      { id: "pr-10", label: "Remove AI-sounding phrases — 'delve', 'leverage', 'crucial', 'realm', 'encompass'", priority: "must" },
      { id: "pr-11", label: "Check flow — content reads smoothly from beginning to end", priority: "must" },
      { id: "pr-12", label: "Review full structure once through the headings", priority: "must" },
      { id: "pr-13", label: "Final word count check", priority: "must" },
      { id: "pr-14", label: "All links are working — no broken links", priority: "must" },
      { id: "pr-15", label: "Numbers and facts double-checked once more", priority: "must" },
      { id: "pr-16", label: "Read content aloud — identify awkward phrases", priority: "should" },
      { id: "pr-17", label: "Read with fresh eyes — a few hours after writing", priority: "should" },
      { id: "pr-18", label: "Plagiarism check done — target 0%", priority: "must" },
      { id: "pr-19", label: "AI content detector check done — high human score required", priority: "should" },
      { id: "pr-20", label: "Final read — would you enjoy reading this yourself?", priority: "must" },
    ],
  },
  {
    id: "final-submission",
    title: "Final Submission Checklist",
    icon: "🚀",
    description: "Confirm all of these before submitting",
    checks: [
      { id: "fs-01", label: "Word count target achieved", priority: "must" },
      { id: "fs-02", label: "All brief instructions followed", priority: "must" },
      { id: "fs-03", label: "Primary keyword properly placed — H1, intro, H2s, conclusion", priority: "must" },
      { id: "fs-04", label: "Secondary keywords included", priority: "must" },
      { id: "fs-05", label: "NLP terms / semantic entities included", priority: "must" },
      { id: "fs-06", label: "Internal links added (min 3)", priority: "must" },
      { id: "fs-07", label: "External links added (2-3 authority sources)", priority: "must" },
      { id: "fs-08", label: "Alt text written for all images", priority: "must" },
      { id: "fs-09", label: "FAQ section with minimum 5 questions", priority: "must" },
      { id: "fs-10", label: "Meta description drafted — 150-160 chars, keyword + CTA", priority: "must" },
      { id: "fs-11", label: "Heading hierarchy correct — H1 > H2 > H3", priority: "must" },
      { id: "fs-12", label: "Plagiarism check done — 0% result", priority: "must" },
      { id: "fs-13", label: "Grammar check done — Grammarly", priority: "must" },
      { id: "fs-14", label: "AI detection check done (if required)", priority: "should" },
      { id: "fs-15", label: "Formatting clean — no extra spaces, consistent headings", priority: "must" },
      { id: "fs-16", label: "All links working", priority: "must" },
      { id: "fs-17", label: "Submitting in correct file format", priority: "must" },
      { id: "fs-18", label: "Submitting before the deadline", priority: "must" },
      { id: "fs-19", label: "Special notes or comments added for SEO manager", priority: "should" },
      { id: "fs-20", label: "Content is genuinely helpful — would you share this article?", priority: "must" },
    ],
  },
];

export const getWriterTotalChecks = () =>
  writerSopData.reduce((total, cat) => total + cat.checks.length, 0);

export const getWriterCategoryProgress = (
  categoryId: string,
  checked: Record<string, boolean>
) => {
  const cat = writerSopData.find((c) => c.id === categoryId);
  if (!cat) return { done: 0, total: 0 };
  const done = cat.checks.filter((ch) => checked[ch.id]).length;
  return { done, total: cat.checks.length };
};

export const getWriterOverallProgress = (checked: Record<string, boolean>) => {
  const total = getWriterTotalChecks();
  const done = Object.values(checked).filter(Boolean).length;
  return { done, total };
};
